### ISSUE TITLE
[Questions] How to use finetune +  enhancement functions + discord

### ISSUE THREAD

**Issue by Jack74r** [erew123/alltalk_tts#108]
Hi
Thank for this project and the documentation. It's not a issue but questions, idk if i can post here, sorry if not

I've succeeded to create a finetune model, but how do I select it? Do I have to replace the existing one?

Is it possible to use the Improve output quality and Resemble enhancement functions like text-generation-webui? 

Is there a discord for this project?

**Comment by erew123** [comment]
Hi @Jack74r 

**discord etc**
You're fine to ask questions here, not an issue! And no I don't have a discord, I don't have enough spare time to setup and maintain it, I do get quite a bit of questions on Reddit too, so between that and here, it keeps me busy enough,

**Finetuned models**
With the finetune models, if you are using them within Text-generation-webui, you will get an option within the interface to load that model https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-using-a-finetuned-model-in-text-generation-webui

If you wish to use the finetuned model generally, you will need to copy it over the top of the existing base model. 

**improved quality**
When you say improved quality, in what way do you mean? Higher Hz output e.g. 44100Hz etc? And when you say " Resemble enhancement functions like text-generation-webui?" I know of resemble enhance, but I dont know of any used in text-generation-webui, have you something you could point/link me to?

Thanks

**Comment by brentjohnston** [comment]
Thanks for the info, I also have a question about this repo version. Currently I am using a custom elevenlabs v2 extension I made and the voice cloning is amazing. I stopped using the built in coqui tts because I could never get good results (and was probably doing something wrong)

I am wondering if this extension would maybe come close to elevenlabs v2, and if it maybe has style and exaggeration options like on elevenlabs v2 sliders. Do you have any general guidelines for training, such as one long 2 minute audio clip. I am going to dive into this again tonight because the elevenlabs v2 is getting too expensive. Any help and info on this would be really appreciated.

**Comment by erew123** [comment]
Hi @brentjohnston 

You will need to go into the finetuned model folder `\alltalk_tts\model\finetuned\` and in there you will find your wav samples folder. Simply copy the wav sample you want to use to the `\alltalk_tts\voices\` folder. I dont set it to automatically move the samples over to this folder, because some people do crazy amounts of training and end up with 100+ voice sample files.

I appreciate I probably could tidy this process up a little or document it further (Ill make a mental note to do that one).

As for emotion control, within the XTTS model there is no direct way to influence it. I may add other models in future that do have those kinds of options.

When you say it just plays the Narrator, are you just using this in the standard chat window of Text-gen? With a character card?

Thanks

**Comment by brentjohnston** [comment]
Thanks for the reply, I did get it working by coping the model over the xttsv2_2.0.2 folder and just using the XTTSv2 Local button. It seems like the XTTSv2 FT button wasn't linking to the newly created trainedmodel folder for some reason.

For that voices folder, I did copy it them all over but the originals are still in there like arnold, do those affect anything or should I be deleting them? Thanks a lot, I can already tell I will probably spend an entire day here tinking with the sample selection, training, temperature, and Repetition Penalty sliders haha.

If you know any lesser-known settings that affect the voice in a script somewhere (not mapped to gradio) would love to know of any other settings worth messing with.

**Comment by brentjohnston** [comment]
Thanks for that in, will try it out for sure. Also have an update, I just trained with whisper v2 this go-around and also used a few two minutes audio clips downloaded from the nearly perfect eleven v2 representation of my voice mixed in. 

I loaded it with the original samples used on elevenlabs and trained over the first finetuning I did a bit ago and that was "ok" for base model. This second trained and just tested it with the chat, this one is actually somehow _better_ than elevenlabs v2, I am pretty mind blow right now. It has more emotion to the voice and sounds exactly like me.

Now the only problem I have though: The built-in sd_api_pictures doesn't seem to work right. For sending pictures to the chat via automatic1111 api. It just read to me a 12 minute clip of jibberish characters from the cmd window somehow (I think that's created from the picture generation) haha. If I can just get that to work again this would be pretty much flawless.

It seems like there's some sort of compatibility issues where the chat says recording a message and just sits there and the picture does eventually come through but the audio is not reading the right thing.

**Comment by erew123** [comment]
The SD issue is due to how Text-gen passes things around in the backend. Ive had a long chat with someone else on this https://github.com/erew123/alltalk_tts/issues/69

Ive yet to setup stripping out and pushing back in the images, which does/should clear up the issue. Just too many things going on at that time with other bits to make the change and resolve it.

Ill try get it done sometime soon.

**Comment by erew123** [comment]
Hi @Jack74r 

Did my earlier response help you or do you need more information? 

Thanks

**Comment by Jack74r** [comment]
Yes thank you

**Comment by brentjohnston** [comment]
> Ive yet to setup stripping out and pushing back in the images, which does/should clear up the issue. Just too many things going on at that time with other bits to make the change and resolve it.


Thank you that would be awesome, the reason I would use this personally is I am dreambooth training images of a product for testing with like 80 photos, it would be really great if could request an image from the chat and it pops up. 

I'm trying to test this comcept out and also train an llm on company data and use my voice for the chat. Thanks a lot.
