### ISSUE TITLE
Ability to easily switch between different finetuned models in standalone mode

### ISSUE THREAD

**Issue by delijoe79** [erew123/alltalk_tts#119]
Currently in standalone mode, the only way to actually load a finetuned model into alltalk tts is to rename the "trainedmodel" folder to something else, then go into the modeldownload.json file and change the model path to that folder so it will then load the finetuned model.

There really should be functionality in the interface to switch to different finetuned models on the fly and the finetuner should be able to save said models into different folders (not just "trainedmodel") so they can be loaded into the tts engine when needed.

I use this for audiobook creation rather then tts for llm chats so this functionality would help me greatly.

**Comment by delijoe79** [comment]
I don't think you understand what I'm trying to say.

When you load up the settings page you only have the option to use the APIs and the base model.  The settings page doesn't give you the option to switch to a finetuned model.

So right now, what I'm doing is when I finetune a model on a specific voice, I rename the folder in the models directory to something else.  So now my directory looks like this:

-models
--xtts2_2.0.2
--voice1
--voice2
...etc..

So when I want to use a specific finetune in the TTS Generator, I go into the modeldownload.json file and change the model_path to the name of the directory where my finetune is, then when I run alltalk the model loaded is from that directory.

What I'm asking is functionality to be able to load a different finetune from a different directory within the model folder either on the settings page or on TTS generator.  Maybe have it so it detects the different model directories and gives you the option to select one on the settings page.

**Comment by brentjohnston** [comment]
`When you load up the settings page you only have the option to use the APIs and the base model. The settings page doesn't give you the option to switch to a finetuned model.`

It does, I had this problem at first too. If you leave everything as it is make sure to click the "XTTSv2 FT" button and it will automatically map to that new trainedmodel folder.

The first time I did it though it didn't change the model to trained model and I just moved base model files and pasted the contents of the new trainedmodel files in the xttsv2_2.0.2 (and selected the XTTSv2 Local in the app, which was now the trained model)

But after I think a reboot, it's working as intended now. It would be nice if any custom folder names in the models folder also showed up in the interface.

**Comment by erew123** [comment]
Hi @delijoe79 

I did get what you were implying, however I could see 2x possible options for what you were asking, so I just wanted to clarify.

Ill think on ways to swap models in that way, however it could be a complicated thing to achieve en masse, partly due to 3rd party scripts that I don't have control over, but as I say I will think about it.

One thing I will add though, is that its perfectly fine to finetune a model on more than 1x voice e.g. you would train a model on 1x voice until you are happy, then you can further train that model on another voice.

The actual base model is trained on 35+ voices already and obviously multiple languages. 

I'm sure there is a breakpoint somewhere down the line, whereby if you've trained it on X amount of new voices it will impact the reproduction of another voice, however, this will be quite a lot of extra trained voices. 

I guess what Im getting at is, finetuning does not restrict the model down to just being able to reproduce that 1x voice you trained it on and as such, you dont need to retain one model per trained voice. So you may wish to try that out and see if it works for you.

Thanks

**Comment by erew123** [comment]
Hi @delijoe79 

As I've not heard back from you Im going to close the ticket for now. I will make a note in the Feature requests about this ticket and a request for additional model handling. Saying that, I am looking at changing the structure of a few things, which may allow an additional level of flexibility for handling situations such as the one you questioned.

Feature requests list is maintained here: https://github.com/erew123/alltalk_tts/discussions/74

Thanks
