### ISSUE TITLE
Issue with installing nvidia-cudnn-cu116

### ISSUE THREAD

**Issue by allenhs** [erew123/alltalk_tts#182]
Hello, I have an updated version of oobabooga and have encountered the following error:

![alltalk](https://github.com/erew123/alltalk_tts/assets/10841863/dd96fb43-be7e-419f-b4fe-5c4e5f37c8be)

My system gpu is an Nvidia 4090 and I am running Windows 11.

**Comment by allenhs** [comment]
Thanks for the reply,

Yeah I manually start the Environment that pinokio creates for Oobabooga, I use install Alltalk for oobabooga all the time with this method.

![image](https://github.com/erew123/alltalk_tts/assets/10841863/6e537817-05b2-442d-83a2-7eff27f31481)

**Comment by erew123** [comment]
Hi @allenhs 

I don't know why Pinokio is set to **(assumedly)** install PyTorch CUDA 11.6, but I don't support PyTorch CUDA 11.6. I'm only supporting the base requirements that text-gen-webui installs, which is either PyTorch CUDA 11.8 or PyTorch CUDA 12.1.

You can confirm your PyTorch version in the following way:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/2f220f92-3ae9-455f-9f47-6aea24f76c78)

The above example shows PyTorch 2.2.1 with cu121, which is CUDA 12.1. Below is an explainer:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/519dcab8-89ff-48ee-950d-0e3fdb733406)

Not knowing Pinokio, I cant say if the PyTorch version is something you (the end user) is something you set up, or if its something Pinokio does as part of its installation routine, either as a system wide setting for Pinokio OR specific to each application it installs.

I can suggest 3x possible routes (in no particular order):

---

1) Upgrade your PyTorch within the Pinokio Python environment to have CUDA 11.8 or 12.1 https://pytorch.org/get-started/locally/

I don't personally use Pinokio so I don't know if this would break anything else. Again, not sure whats installed/setup the curren PyTorch w/ CUDA 11.6 environment.

You would run cmd_windows.bat and then run the correct PyTorch command from the Pytorch website.

---

2) Edit the `\alltalk_tts\system\requirements\requirements_textgen.txt` removing:
```
nvidia-cublas-cu11>=11.11.3.6
nvidia-cudnn-cu11>=9.0.0.312
```

From the file. The net effect of doing this, is that you wouldn't be able to use finetuning without performing a manual installation of the Nvidia CUDA Toolkit (As detailed in the Finetuning documentation).

---

3) Speak to the person who developed/setup the Pinokio Text-gen-webui and ask them why it appears to be using PyTorch CUDA 11.6. 

---

As I say, my best guess is that somehow you have PyTorch with CUDA 11.6 on your system, due to the fact the the PIP installer is trying to install `nvidia-cudnn-cu11` for PyTorch with CUDA 11.6 (As below cu116).

![image](https://github.com/erew123/alltalk_tts/assets/35898566/1bfb19b6-d6e9-4f0c-9ca7-68599b0800c9)

If you had PyTorch with CUDA 11.8 (cu118) or CUDA 12.1 (cu121) it would be attempting to install those versions. 

Just as an addition, not using PyTorch with CUDA 12.1 will give you quite a performance drop, esp if you are using an RTX based GPU.

**Comment by allenhs** [comment]
Hi @erew123,

It looks like oobabooga is using 2.2.1+cu121. Maybe Pinokio is doing some other weird thing under the hood.

![image](https://github.com/erew123/alltalk_tts/assets/10841863/cce6839a-d461-4b12-b193-1815f378aee2)

Given that it was reporting a good version, I decided to go with option 3 and it seems to have worked great. Thank you for helping, especially given that the root of the problem is outside of Alltalk.
