### ISSUE TITLE
Multiple Generations at once.

### ISSUE THREAD

**Issue by RenNagasaki** [erew123/alltalk_tts#194]
As I plan to use a self hosted variation of this service, I'd like to be able to request more than one generation at once.
My use case is that more than one user could request a dialog to be voiced, at the moment I can only generate one by one, but that hinders it substantially.

**Describe the solution you'd like**
-> The ability to request multiple generations at once as long as the hardware can manage.

**Describe alternatives you've considered**
Hosting multiple instances of the tool and queuing on my end.

**Comment by erew123** [comment]
Hi @RenNagasaki 

Technically this is already in the Features request list [here](https://github.com/erew123/alltalk_tts/discussions/74)

![image](https://github.com/erew123/alltalk_tts/assets/35898566/32f24d33-b3da-4c57-8606-28eeda06b6a4)

But let me ask you a question based on your scenario. When you say "multiple generations" do you mean you:

A) are happy for each generation to queue up behind one another, so if say 3x generation requests come in, they would be queued, but served in the order they came in? So basically, a queuing system.

or 

B), You want it to start generating request 1 and if request 2 and request 3 come in while request 1 is still processing, you want it to immediately start work on request 2 and 3, So parallel generation.

Or would either A OR B work?

A should definitely be possible. B I've not looked into how possible this will be, there may be limitations here because of the Coqui scripts/engine that I cannot get around (or any other TTS engines I will be hopefully adding).

What I can say however, is that version 2 is very much in process being coded, though I am hoping to have a lot of new features added/coded in the next big release, (hopefully) including most of the Features request list, plus resolving lots of other little niggles/issues Ive had along the way e.g. with the API requests, you can set defaults, so if something isn't provided in a generation request, it will just use the default that you set. Im also trying to make it modular to a degree, so there will be a base of AllTalk and then you can choose what other modules (or TTS engines) to load/use, so hopefully you can keep it as lightweight as you want. Better discovery of models available for loading etc and so on and so forth.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/88aac592-8928-4a4f-9700-7df746b87e89)

Thanks

**Comment by erew123** [comment]
Im going to close this for now as we discussed it elsewhere.

**Comment by mercuryyy** [comment]
@erew123 I think A would be great, but if you can manage to get B to work and having parallel generation this can really be amazing for what we are trying to do. 

Any time frame on the big v2 release? and can you update if you where able to test parallel generation? 


Thank you so much!

**Comment by mercuryyy** [comment]
@erew123 Thank you for the detailed response your doing amazing work with this repo.

I think even if you start with the option to load multiple model.pth into ram this would be a great addon that we can build on. 

Parallel requests is probably the most important thing for production.

Thank you for the update!
