### ISSUE TITLE
DeepSpeed Won't Install!

### ISSUE THREAD

**Issue by sigma7eaven** [erew123/alltalk_tts#199]
🔴 If you have installed AllTalk in a custom Python environment, I will only be able to provide limited assistance/support. AllTalk draws on a variety of scripts and libraries that are not written or managed by myself, and they may fail, error or give strange results in custom built python environments. Seems un related.

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration. If I work this out will add later?

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**
  atsetup.bat Deepspeed Install Fail

   Please ensure you have started your Text-generation-webui Python
   environment. If you have NOT done this, please run cmd_windows.bat
   in the text-generation-webui folder and then re-run this script.

   
**To Reproduce**
Steps to reproduce the behaviour: Choose option 6

**Screenshots**

**Text/logs**
If applicable, copy/paste in your logs here from the console.
BASE REQUIREMENTS
   1) Apply/Re-Apply the requirements for Text-generation-webui.

   OPTIONAL
   2) Git Pull the latest AllTalk updates from Github

   DEEPSPEED FOR PyTorch 2.1.x
   4) Install DeepSpeed v11.2 for CUDA 11.8 and Python-3.11.x and PyTorch 2.1.x.
   5) Install DeepSpeed v11.2 for CUDA 12.1 and Python-3.11.x and PyTorch 2.1.x.

   DEEPSPEED FOR PyTorch 2.2.x (March 2024 builds of Text-gen-webui and later)
   6) Install DeepSpeed v14.0 for CUDA 12.1 and Python-3.11.x and PyTorch 2.2.x.
   7) Install DeepSpeed v14.0 for CUDA 11.8 and Python-3.11.x and PyTorch 2.2.x.

   U) Uninstall DeepSpeed.

   OTHER
   8) Generate a diagnostics file.

   9) Exit/Quit

Enter your choice: 6
Downloading DeepSpeed...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

   Failed to download DeepSpeed wheel file.
   Please check your internet connection or try again later.
   Press any key to return to the menu.

Press any key to continue . . .
BASE REQUIREMENTS
   1) Apply/Re-Apply the requirements for Text-generation-webui.

   OPTIONAL
   2) Git Pull the latest AllTalk updates from Github

   DEEPSPEED FOR PyTorch 2.1.x
   4) Install DeepSpeed v11.2 for CUDA 11.8 and Python-3.11.x and PyTorch 2.1.x.
   5) Install DeepSpeed v11.2 for CUDA 12.1 and Python-3.11.x and PyTorch 2.1.x.

   DEEPSPEED FOR PyTorch 2.2.x (March 2024 builds of Text-gen-webui and later)
   6) Install DeepSpeed v14.0 for CUDA 12.1 and Python-3.11.x and PyTorch 2.2.x.
   7) Install DeepSpeed v14.0 for CUDA 11.8 and Python-3.11.x and PyTorch 2.2.x.

   U) Uninstall DeepSpeed.

   OTHER
   8) Generate a diagnostics file.

   9) Exit/Quit

Enter your choice: 6
Downloading DeepSpeed...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

   Failed to download DeepSpeed wheel file.
   Please check your internet connection or try again later.
   Press any key to return to the menu.

Press any key to continue . . .

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date] Aquired within past few weeks
Custom Python environment: [yes/no give details if yes] Python 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)] on win32
Text-generation-webUI was updated: [approx.] latest release within last week 

**Additional context**
I'm getting the same error from pip install deepspeed

**Comment by sigma7eaven** [comment]
Enter your choice: 8

Select a requirements file to check against (or press Enter for default 'requirements.txt'):

    1. requirements_docker.txt
    2. requirements_googlecolab.txt
    3. requirements_standalone.txt
    4. requirements_textgen.txt

Enter the number of your choice:
May be I needed to run one of these still? Using AllTalk incorporated with web interface ui not the standalone. Did I still need to run the text gen requirements maybe?

**Comment by sigma7eaven** [comment]
ok you can probably close this I've found a guide on the epic mission involved in making deepspeed work on windows, thanks for the great plug in btw.
https://github.com/microsoft/DeepSpeed/issues/4729

**Comment by sigma7eaven** [comment]
interesting new problem!
18:20:55-935677 INFO     Starting Text generation web UI
18:20:55-940678 INFO     Loading settings from "settings.yaml"
18:20:55-946679 INFO     Loading the extension "gallery"
18:20:55-948680 INFO     Loading the extension "coqui_tts"
[XTTS] Loading XTTS...
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
[XTTS] Done!
18:21:18-828909 INFO     Loading the extension "whisper_stt"

Running on local URL:  http://127.0.0.1:7860

Closing server running on port: 7860
18:44:24-876753 INFO     Loading the extension "gallery"
18:44:24-880754 INFO     Loading the extension "whisper_stt"
18:44:24-882755 INFO     Loading the extension "alltalk_tts"
[AllTalk Startup]     _    _ _ _____     _ _       _____ _____ ____
[AllTalk Startup]    / \  | | |_   _|_ _| | | __  |_   _|_   _/ ___|
[AllTalk Startup]   / _ \ | | | | |/ _` | | |/ /    | |   | | \___ \
[AllTalk Startup]  / ___ \| | | | | (_| | |   <     | |   | |  ___) |
[AllTalk Startup] /_/   \_\_|_| |_|\__,_|_|_|\_\    |_|   |_| |____/
[AllTalk Startup]
[AllTalk Startup] Config file check      : No Updates required
Traceback (most recent call last):
  File "C:\Code\text-generation-webui-main\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Code\text-generation-webui-main\extensions\alltalk_tts\script.py", line 130, in <module>
    import deepspeed
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\site-packages\deepspeed\__init__.py", line 9, in <module>
    from .runtime.engine import DeepSpeedEngine
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\site-packages\deepspeed\runtime\engine.py", line 12, in <module>
    from tensorboardX import SummaryWriter
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\site-packages\tensorboardX\__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\site-packages\tensorboardX\torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\site-packages\tensorboardX\writer.py", line 15, in <module>
    from .event_file_writer import EventFileWriter
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\site-packages\tensorboardX\event_file_writer.py", line 28, in <module>
    from .proto import event_pb2
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\site-packages\tensorboardX\proto\event_pb2.py", line 15, in <module>
    from tensorboardX.proto import summary_pb2 as tensorboardX_dot_proto_dot_summary__pb2
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\site-packages\tensorboardX\proto\summary_pb2.py", line 15, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\site-packages\tensorboardX\proto\tensor_pb2.py", line 15, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\site-packages\tensorboardX\proto\resource_handle_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Code\text-generation-webui-main\installer_files\env\Lib\site-packages\google\protobuf\descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Running on local URL:  http://127.0.0.1:7860

Trying to get microsoft stuff to run on window haha.

**Comment by erew123** [comment]
Hi @sigma7eaven 

Without a diagnostic file Im unable to say what version of Pytorch you are running. I do however provide versions of precompiled deepspeed e.g. https://github.com/erew123/alltalk_tts/releases/tag/DeepSpeed-14.0

There is also a main section of the front Github page related to DeepSpeed compilation and setup https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-deepspeed-installation-options

Regarding the **"curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012)"** this is am issue relating to your internet connection and something being filtered between yourself and girhub or a github problem. I answered this and discussed it with someone else on this [ticket here](https://github.com/erew123/alltalk_tts/issues/151#issuecomment-2027822983)

That aside, DeepSpeed has to be compiled correctly for the version of PyTorch and the Python requirements you have on your system otherwise it will error. I know that PyTorch 2.3.x has recently been released, though I am not sure if Text-gen-webui has moved up to that version currently. I would need a diagnostics report from your system to be able to understand your Python environment, You can run it against the "requirements_textgen.txt" file. 

Thanks

**Comment by sigma7eaven** [comment]
I see all the package miss matching I re apply the extensions\alltalk_tts\system\requirements requirements_textgen.txt and the C:\deepspeed\requirements requirements for DeepSpeed. I tried to update my base package from python 3.10 to 3.11 python -v shows 3.11 but diagnostics showing 3.10?

**Comment by erew123** [comment]
Hi @sigma7eaven 

The main issue is that you have `Torch Version: 2.3.0+cu121` torch 2.3.0, though its also fair to say the Python version may matter.

So, DeepSpeed has to be compiled/built specific to a machines Python environment. Its basically a real pain. You can get away with point revisions of things with DeepSpeed e.g. if its compiled for Pytorch 2.2.1 then it will be fine with Pytorch 2.2.2 and Pytorch 2.2.3, but it wont be fine with Pytorch 2.**3**.x 

Because the only way to compile/build DeepSpeed is to actually create that Python environment that you want to compile it for, well that takes time as you have to install the Python version, then all the underlying bits like PyTorch with the CUDA version you want etc etc. In short, that means if you wanted to build for Python 3.10 with CUDA 11.8 and then CUDA 12.1, that's already 2x environments you have to build, but then you have the complexity of the PyTorch versions, so if you want to build for Pytorch 2.1.x, 2.2.x, 2.3.x then that's now 12x Python environments you have to build to cover all variables. Plus the build time of DeepSpeed. Aka, just doing that alone would be about 12 hours work.

As such, I only build DeepSpeed versions for whatever Text-generation-webui is currently installing as a default installation.

I want to be 1000% clear here Python environments are complicated and a pain in the ass. They are very easy to screw up and can be a real pain to get your head around. I have no idea of your understanding or tech abilities, I would only advise doing what you personally feel comfortable with and I will be unable to support you to a deep level with this. AKA you do any changes at your own risk. There is a short Python environments primer here https://github.com/erew123/alltalk_tts?tab=readme-ov-file#installation-and-setup-issues which I wrote. But as I say, **at your own risk**.

So, you have 4x choices from here:

---

1) I am currently attempting to build a DeepSpeed version based on Python 3.11.x Pytorch 2.3.x and CUDA 12.1.

If it builds and when I upload it, you can try that version. It may or may not be happy about you being on Python version being 3.10. 

--- 

2) You can force a downgrade of your Pytorch version in Text-gen-webui. You would run `cmd_windows.bat` to start your python environment. Uninstall torch 
`pip uninstall torch` 
`pip uninstall torchaudio` 
and then force Pytorch 2.2.1 to install 
`pip install torch>=2.2.1+cu121 torchaudio>=2.2.1+cu121 --upgrade --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu1` 
which would support the version of DeepSpeed I linked to earlier. https://github.com/erew123/alltalk_tts/releases/tag/DeepSpeed-14.0

Again, it may not be happy about being on Python 3.10

---

3) If its not happy about your Python version, the only way to update Python within a Conda Python environment, is to build a new Conda Python environment with a later version of Python. Doing that manually would be a pain in the ass. The simplest way of doing it, would be to `git pull` inside your text-gen-webui folder to make sure you are up to date and then delete the `installer_files` folder and run `start_windows.bat`

![image](https://github.com/erew123/alltalk_tts/assets/35898566/17cfb9f2-3c23-4768-976a-d5b0dc01fc7c)

When you run the `start_windows.bat` it will build a entirely new Conda Python environment. You **will** have to reinstall any requirements files for any extensions you have installed (including AllTalk).

You would however find that it installs a new, up to date Python environment:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/29eb6b89-f69b-497b-b686-3376df3f9cd5)

However, I will still need to compile a new version of DeepSpeed before it will work on Pytorch 2.3.x

---

4) You can compile your own version of DeepSpeed, specific to your current build by following the instructions here https://github.com/S95Sedan/Deepspeed-Windows

Thanks

**Comment by sigma7eaven** [comment]
RESULT
pip install protobuf==3.20.*

This helped a lot, only thing is it says Deepspeed version can't be detected... And port issue duplicate connection.

I still have to read your reply just wanted to show the progress.

23:08:07-129772 INFO     Starting Text generation web UI
23:08:07-134773 INFO     Loading settings from "settings.yaml"
23:08:07-139774 INFO     Loading the extension "gallery"
23:08:07-141775 INFO     Loading the extension "coqui_tts"
[XTTS] Loading XTTS...
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
[XTTS] Done!
23:08:30-190189 INFO     Loading the extension "whisper_stt"

Running on local URL:  http://127.0.0.1:7860

Closing server running on port: 7860
23:13:43-316139 INFO     Loading the extension "gallery"
23:13:43-320140 INFO     Loading the extension "whisper_stt"
23:13:43-322140 INFO     Loading the extension "alltalk_tts"
[AllTalk Startup]     _    _ _ _____     _ _       _____ _____ ____
[AllTalk Startup]    / \  | | |_   _|_ _| | | __  |_   _|_   _/ ___|
[AllTalk Startup]   / _ \ | | | | |/ _` | | |/ /    | |   | | \___ \
[AllTalk Startup]  / ___ \| | | | | (_| | |   <     | |   | |  ___) |
[AllTalk Startup] /_/   \_\_|_| |_|\__,_|_|_|\_\    |_|   |_| |____/
[AllTalk Startup]
[AllTalk Startup] Config file check      : No Updates required
[AllTalk Startup] AllTalk startup Mode   : Text-Gen-webui mode
[AllTalk Startup] WAV file deletion      : Disabled
[AllTalk Startup] DeepSpeed version      : Not Detected
[AllTalk Startup] Model is available     : Checking
[AllTalk Startup] Model is available     : Checked
[AllTalk Startup] Current Python Version : 3.11.9
[AllTalk Startup] Current PyTorch Version: 2.2.1+cu121
[AllTalk Startup] Current CUDA Version   : 12.1
[AllTalk Startup] Current TTS Version    : 0.22.0
[AllTalk Startup] Current TTS Version is : Up to date
[AllTalk Startup] AllTalk Github updated : 1st May 2024 at 15:09
[AllTalk Startup] TTS Subprocess         : Starting up
[AllTalk Startup]
[AllTalk Startup] AllTalk Settings & Documentation: http://127.0.0.1:7851
[AllTalk Startup]
[AllTalk Model] XTTSv2 Local Loading xttsv2_2.0.2 into cuda
[AllTalk Model] Coqui Public Model License
[AllTalk Model] https://coqui.ai/cpml.txt
[AllTalk Model] Model Loaded in 20.25 seconds.
[AllTalk Model] Ready
ERROR:    [Errno 10048] error while attempting to bind on address ('127.0.0.1', 7851): only one usage of each socket address (protocol/network address/port) is normally permitted

Running on local URL:  http://127.0.0.1:7860

**Comment by erew123** [comment]
Hi @sigma7eaven 

I've tested compiling DeepSpeed for PyTorch 2.3.x and it just wont at the moment. Something to do with `flash_attn` needing additional compilation for the new 2.5.8 version (which takes about 1 hour or longer and the Nvidia CUDA Toolkit).

I've wiped and reinstalled text-gen-webui fresh and it currently installs:

PYTHON & PYTORCH:
 Torch Version: 2.2.1+cu121
 Python Version: 3.11.8
 flash_attn>= 2.5.6

![image](https://github.com/erew123/alltalk_tts/assets/35898566/22649300-abcf-449e-bffa-5a6ad71a8e2c)

As such, as your system is showing PyTorch 2.3.0 see your post [here](https://github.com/erew123/alltalk_tts/issues/199#issuecomment-2091532742) I would suggest the **"option 3"** route that I listed above as that would at least get you to a factory stage.

Until there is a clear/easy way to compile flash_attn 2.5.8 that doesn't require 1+hours time on a persons system, I cant see an upgrade package for DeepSpeed on Windows to support PyTorch 2.3.x.

I also believe that the flash_attn will also impact some of text-gen-webui's loaders e.g. ExLlama etc, so upgrading it anyway isnt a good option until those have been flagged as working.

For reference, here is the current full package list that Text-gen-webui installs for Nvidia card systems running CUDA 12.1

PYTHON PACKAGES:
 absl-py>= 2.1.0
 accelerate>= 0.27.2
 aiofiles>= 23.2.1
 aiohttp>= 3.9.3
 aiosignal>= 1.3.1
 altair>= 5.3.0
 annotated-types>= 0.6.0
 anyascii>= 0.3.2
 anyio>= 4.3.0
 appdirs>= 1.4.4
 attrs>= 23.2.0
 audioread>= 3.0.1
 autoawq>= 0.2.3
 autoawq_kernels>= 0.0.6
 auto-gptq>= 0.6.0+cu121
 av>= 11.0.0
 Babel>= 2.14.0
 bangla>= 0.0.2
 bitsandbytes>= 0.43.0
 blinker>= 1.7.0
 blis>= 0.7.11
 bnnumerizer>= 0.0.2
 bnunicodenormalizer>= 0.1.6
 catalogue>= 2.0.10
 certifi>= 2024.2.2
 cffi>= 1.16.0
 chardet>= 5.2.0
 charset-normalizer>= 3.3.2
 click>= 8.1.7
 cloudpathlib>= 0.16.0
 colorama>= 0.4.6
 coloredlogs>= 15.0.1
 confection>= 0.1.4
 contourpy>= 1.2.0
 coqpit>= 0.0.17
 cramjam>= 2.8.3
 ctransformers>= 0.2.27+cu121
 ctranslate2>= 4.1.0
 cutlet>= 0.4.0
 cycler>= 0.12.1
 cymem>= 2.0.8
 Cython>= 3.0.10
 DataProperty>= 1.0.1
 datasets>= 2.18.0
 dateparser>= 1.1.8
 decorator>= 5.1.1
 deepspeed>= 0.14.0+ce78a63
 dill>= 0.3.8
 diskcache>= 5.6.3
 distro>= 1.9.0
 docker-pycreds>= 0.4.0
 docopt>= 0.6.2
 einops>= 0.7.0
 encodec>= 0.1.1
 en-core-web-md>= 3.7.1
 exllamav2>= 0.0.15+cu121
 fastapi>= 0.110.0
 faster-whisper>= 1.0.1
 fastparquet>= 2024.2.0
 ffmpy>= 0.3.2
 filelock>= 3.9.0
 flash_attn>= 2.5.6
 Flask>= 3.0.2
 flask-cloudflared>= 0.0.14
 flatbuffers>= 24.3.25
 fonttools>= 4.50.0
 frozenlist>= 1.4.1
 fsspec>= 2024.2.0
 fugashi>= 1.3.1
 fuzzywuzzy>= 0.18.0
 g2pkk>= 0.1.2
 gekko>= 1.1.0
 gitdb>= 4.0.11
 GitPython>= 3.1.43
 gptq-for-llama>= 0.1.1+cu121
 gradio>= 4.26.0
 gradio_client>= 0.15.1
 grpcio>= 1.62.1
 gruut>= 2.2.3
 gruut-ipa>= 0.13.0
 gruut-lang-de>= 2.0.0
 gruut-lang-en>= 2.0.0
 gruut-lang-es>= 2.0.0
 gruut-lang-fr>= 2.0.2
 h11>= 0.14.0
 hangul-romanize>= 0.1.0
 hjson>= 3.1.0
 hqq>= 0.1.5
 httpcore>= 1.0.5
 httpx>= 0.27.0
 huggingface-hub>= 0.22.2
 humanfriendly>= 10.0
 idna>= 3.6
 importlib_metadata>= 7.1.0
 importlib_resources>= 6.4.0
 inflect>= 7.2.0
 itsdangerous>= 2.1.2
 jaconv>= 0.3.4
 jamo>= 0.4.1
 jieba>= 0.42.1
 Jinja2>= 3.1.2
 joblib>= 1.3.2
 jsonlines>= 1.2.0
 jsonschema>= 4.21.1
 jsonschema-specifications>= 2023.12.1
 kiwisolver>= 1.4.5
 langcodes>= 3.3.0
 lazy_loader>= 0.3
 Levenshtein>= 0.25.0
 librosa>= 0.10.1
 llama_cpp_python>= 0.2.56+cpuavx2
 llama_cpp_python_cuda>= 0.2.56+cu121
 llama_cpp_python_cuda_tensorcores>= 0.2.56+cu121
 llvmlite>= 0.42.0
 lm-eval>= 0.3.0
 Markdown>= 3.6
 markdown-it-py>= 3.0.0
 MarkupSafe>= 2.1.3
 matplotlib>= 3.8.3
 mbstrdecoder>= 1.1.3
 mdurl>= 0.1.2
 mojimoji>= 0.0.13
 more-itertools>= 10.2.0
 mpmath>= 1.3.0
 msgpack>= 1.0.8
 multidict>= 6.0.5
 multiprocess>= 0.70.16
 murmurhash>= 1.0.10
 networkx>= 2.8.8
 ninja>= 1.11.1.1
 nltk>= 3.8.1
 num2words>= 0.5.13
 numba>= 0.59.1
 numexpr>= 2.9.0
 numpy>= 1.26.4
 nvidia-cublas-cu11>= 11.11.3.6
 nvidia-cuda-nvrtc-cu11>= 11.8.89
 nvidia-cudnn-cu11>= 9.0.0.312
 onnxruntime>= 1.17.1
 openai>= 1.14.3
 optimum>= 1.17.1
 orjson>= 3.10.0
 packaging>= 24.0
 pandas>= 1.5.3
 pathvalidate>= 3.2.0
 peft>= 0.8.2
 pillow>= 10.3.0
 pip>= 23.3.1
 platformdirs>= 4.2.0
 pooch>= 1.8.1
 portalocker>= 2.8.2
 preshed>= 3.0.9
 protobuf>= 4.25.3
 psutil>= 5.9.8
 pyarrow>= 15.0.2
 pyarrow-hotfix>= 0.6
 pybind11>= 2.12.0
 pycountry>= 23.12.11
 pycparser>= 2.22
 pydantic>= 2.6.4
 pydantic_core>= 2.16.3
 pydub>= 0.25.1
 Pygments>= 2.17.2
 pynndescent>= 0.5.12
 pynvml>= 11.5.0
 pyparsing>= 3.1.2
 pypinyin>= 0.51.0
 pyreadline3>= 3.4.1
 pysbd>= 0.3.4
 pytablewriter>= 1.2.0
 python-crfsuite>= 0.9.10
 python-dateutil>= 2.9.0.post0
 python-Levenshtein>= 0.25.0
 python-multipart>= 0.0.9
 pytz>= 2024.1
 pywin32>= 306
 PyYAML>= 6.0.1
 py-cpuinfo>= 9.0.0
 rapidfuzz>= 3.7.0
 referencing>= 0.34.0
 regex>= 2023.12.25
 requests>= 2.31.0
 rich>= 13.7.1
 rouge>= 1.0.1
 rouge-score>= 0.1.2
 rpds-py>= 0.18.0
 ruff>= 0.3.4
 sacrebleu>= 1.5.0
 safetensors>= 0.4.2
 scikit-learn>= 1.4.1.post1
 scipy>= 1.12.0
 semantic-version>= 2.10.0
 sentencepiece>= 0.2.0
 sentry-sdk>= 1.44.0
 setproctitle>= 1.3.3
 setuptools>= 68.2.2
 shellingham>= 1.5.4
 six>= 1.16.0
 smart-open>= 6.4.0
 smmap>= 5.0.1
 sniffio>= 1.3.1
 sounddevice>= 0.4.6
 soundfile>= 0.12.1
 soxr>= 0.3.7
 spacy>= 3.7.4
 spacy-legacy>= 3.0.12
 spacy-loggers>= 1.0.5
 SpeechRecognition>= 3.10.0
 sqlitedict>= 2.1.0
 srsly>= 2.4.8
 sse-starlette>= 1.6.5
 starlette>= 0.36.3
 SudachiDict-core>= 20240109
 SudachiPy>= 0.6.8
 sympy>= 1.12
 tabledata>= 1.3.3
 tcolorpy>= 0.1.4
 tensorboard>= 2.16.2
 tensorboard-data-server>= 0.7.2
 termcolor>= 2.4.0
 thinc>= 8.2.3
 threadpoolctl>= 3.4.0
 tiktoken>= 0.6.0
 timm>= 0.9.16
 tokenizers>= 0.15.2
 tomlkit>= 0.12.0
 toolz>= 0.12.1
 torch>= 2.2.1+cu121
 torchaudio>= 2.2.1+cu121
 torchvision>= 0.17.1+cu121
 tqdm>= 4.66.2
 tqdm-multiprocess>= 0.0.11
 trainer>= 0.0.36
 transformers>= 4.39.2
 TTS>= 0.22.0
 typeguard>= 4.2.1
 typepy>= 1.3.2
 typer>= 0.9.4
 typer-cli>= 0.12.0
 typer-slim>= 0.12.0
 typing_extensions>= 4.10.0
 tzdata>= 2024.1
 tzlocal>= 5.2
 umap-learn>= 0.5.5
 Unidecode>= 1.3.8
 unidic-lite>= 1.0.8
 urllib3>= 2.2.1
 uvicorn>= 0.29.0
 wandb>= 0.16.5
 wasabi>= 1.1.2
 weasel>= 0.3.4
 websockets>= 11.0.3
 Werkzeug>= 3.0.1
 wheel>= 0.41.2
 xxhash>= 3.4.1
 yarl>= 1.9.4
 zipp>= 3.18.1
 zstandard>= 0.22.0

Thanks
