### ISSUE TITLE
Stuck at Running in Docker

### ISSUE THREAD

**Issue by bollerdominik** [erew123/alltalk_tts#209]
Hi
I am trying to run AllTalkTTS in the cloud. I got a basic RunPod pod (A40) with pytorch. I was able to install the standalone version without errors with `./atsetup.sh `. However, when starting it it gets stuck at Running in Docker

![image](https://github.com/erew123/alltalk_tts/assets/11059476/5027033d-bd6c-4923-841b-b6cfbf0a9ade)

Any ideas?

**Comment by erew123** [comment]
Hi @bollerdominik 

I didn't personally add the docker detection/setup/routines to AllTalk and they are something I am looking to tidy up/resolve on v2 of AllTalk (currently in development).

However, as for your specific issue, its obviously detecting the environment variable `/.dockerenv` in the system you are running it on. If you are able to edit/change the `script.py` file, I can give you a quick fix to see if if gets it working for you!

In script.py in line 305, change the word `dockerenv` to something else (that doesn't exist) and it should bypass that check.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/86a453c8-e836-479f-8fa4-14ce56ea4e10)

e.g. change

`if os.path.isfile("/.dockerenv"):`

to

`if os.path.isfile("/.novariablehere"):`

And that should just cause it to bypass that check, as it wont detect an environment variable called `novariablehere`

As I say, long term I am looking to resolve these issues in V2, due to certain complexities with docker in v1 that have made it too hard to simply resolve.

Hopefully that should solve it for you. Ill close the ticket for now, but feel free to get back to me if you need.

Thanks
