### ISSUE TITLE
Warning Audio generation failed. Status: Error opening 'extensions/alltalk_tts/outputs/Amaya_1715268437.wav': System error.

### ISSUE THREAD

**Issue by Kafkanistan** [erew123/alltalk_tts#212]
Warning Audio generation failed. Status: Error opening 'extensions/alltalk_tts/outputs/Amaya_1715268437.wav': System error.

Diagnotics log:
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/15264365/diagnostics.log)

**Describe the bug**
It doesn't output any sound or generate or wav file. 
Warning Audio generation failed. Status: Error opening 'extensions/alltalk_tts/outputs/Amaya_1715268437.wav': System error.

**To Reproduce**
Start Text generation webui, load in a model, load in a character. Go to chat and type.

**Text/logs**
[cmd.log](https://github.com/erew123/alltalk_tts/files/15264341/cmd.log)

**Desktop (please complete the following information):**
AllTalk was updated: [2024-05-09]
Custom Python environment: [yes/no give details if yes]

Text-generation-webUI was updated: [[2024-05-09]

**Additional context**
When I for example enable deespeed it says it loud DEEPSPEED ENABLED.
Using the preview function does only generate the text in the cmd window but doesn't make any sounds.

**Comment by erew123** [comment]
Hi @Kafkanistan 

I believe its because your folder name has a `-main` on the end of it.

`D:\AI\text-generation-webui-main\extensions\`**`alltalk_tts-main`**

and if you notice, its looking for the output in:

`extensions/`**`alltalk_tts`**`/outputs/Amaya_1715268437.wav`

Its an unfortunate annoyance of downloading off Github as a source code zip file (which is why I recommend a `git clone` as the best way to setup from Github). Python/Conda has some issues with dashes and spaces which cause these complications within the code handling.

If you rename your folder:

D:\AI\text-generation-webui-main\extensions\**alltalk_tts**

and change your extension loading name in Text-gen-webui from **alltalk_tts-main** to **alltalk_tts** then all should be working for you.

Thanks
