### ISSUE TITLE
Request: Silent installer

### ISSUE THREAD

**Issue by RenNagasaki** [erew123/alltalk_tts#277]
Hey.
since I'm currently on the road to make my program usable for non techies I'd love it if there was a bat which would do the same as atsetup.bat but without me or the user needing to input 2 and then 1 for standalone install.
I could create one for myself, but I guess other people would find that useful as well. That's why I'm asking here for it. 😄 

If you don't mind me creating a PR, I could still create that myself.

**Comment by erew123** [comment]
@RenNagasaki is this something you want the user to run or something you want your own install to kick off? Just thinking about where best to store it and a few other details. As mentioned travelling atm, my replies may be slow.

thanks

**Comment by RenNagasaki** [comment]
@erew123 I'd love to kick that off myself.

**Comment by erew123** [comment]
Cant update github atm. In atsetup.bat, try adding

Lines 6-7

`:: Check for "-silent" install command-line argument`
`if "%1"=="-silent" goto InstallCustomStandalone`

Line 452 ish after `echo` before `pause`

`if "%1"=="-silent" goto End`

Will still need running from the alltalk_tts folder.

**Comment by erew123** [comment]
Ive added this into the windows batch file. Ill need to get to a Linux machine at some time to add it onto the Linux script.

Should work fine though for Windows. Ive moved the check for the "-silent" a bit further down the batch file, to make sure some of the basic checks are performed, so that error messages are shown for any configuration/setup issues e.g. folder path has spaces etc.

**Comment by RenNagasaki** [comment]
Thank you very much @erew123! 😄
