### ISSUE TITLE
Can you release pre-compiled latest DeepSpeed for Python 3.10? I see only for Python 3.11

### ISSUE THREAD

**Issue by FurkanGozukara** [erew123/alltalk_tts#283]
Can you please publish also Python 3.10 DeepSpeed? Thank you

**Comment by erew123** [comment]
Hi @FurkanGozukara 

Im only building DeepSpeed now for the Python version that I am focusing on as it takes too much of my time to be demolishing/building different Python environments to compile DeepSpeed up, due to all the variations needed to compile it with. 

There is a Windows **DeepSpeed v11.2** build for Python 3.10, for both CUDA 11.8 and 12.1 here https://github.com/erew123/alltalk_tts/releases/tag/deepspeed

If you would like to compile your own **Windows** version of DeepSpeed, the instructions are now here https://github.com/S95Sedan/Deepspeed-Windows

Linux Versions are here https://github.com/erew123/alltalk_tts/releases/tag/DeepSpeed-14.2-Linux

Thanks

**Comment by FurkanGozukara** [comment]
thanks for answer @erew123 my other question is do you know anyone publishing pre-compiled triton? deepspeed said they gonna support windows soon but for triton i cant find any

**Comment by erew123** [comment]
Im pretty sure Triton is Linux only https://github.com/triton-lang/triton/?tab=readme-ov-file#compatibility

**Comment by FurkanGozukara** [comment]
@erew123 yes they don't support but there was a guy published pre compiled wheels
He sadly abandoned after 2.1
