### ISSUE TITLE
V2 Beta fresh install will continue to download models as if the first time load.

### ISSUE THREAD

**Issue by beeblebrox** [erew123/alltalk_tts#329]
**Describe the bug**
After a fresh install and first time startup if you select xtts it will download the models.  Then if you restart (ctrl-c, rerun start_alltalk.bat) after the server is up and running and even after changing a global setting (in my case enabling rvc) the next run will still have a first time prompt for the model to download and then download the models a second time for xtts.  After I downloaded the piper models it stopped prompting me on other restarts.

**To Reproduce**
Steps to reproduce the behaviour:  See above description.

**Desktop (please complete the following information):**
AllTalk was updated: 15th August 2024 at 08:27
Custom Python environment: ish, had to change requirements_parler.txt to have  `git+https://github.com/huggingface/parler-tts.git@862f84181589ea980d41d279ec53841bc8e178d2^` to workaround conflicting dependency issues (different issue)

Text-generation-webUI was updated:  NA

**Additional context**
This is from a fresh install, and seems very reproducible if selecting xtts on that first prompt and don't download any other models before the next restart.

**Comment by erew123** [comment]
Hi @beeblebrox 

Not sure why it wasnt flagging that first run had completed, though I have doubled the code that marks the firstrun has been completed https://github.com/erew123/alltalk_tts/commit/57a6b3ba3936ecde7362303104c36de3f77afd28

![image](https://github.com/user-attachments/assets/83fc6855-9a3d-4bc3-a602-593e9e517450)

So that should definitely catch it.

Re the Parler/Transformers messages, I have covered that in this ticket here https://github.com/erew123/alltalk_tts/issues/332 so wont repeat here.

Thanks
