### ISSUE TITLE
[alltalkbeta] Parler TTS module not found error on fresh install

### ISSUE THREAD

**Issue by teddybear082** [erew123/alltalk_tts#331]
🔴 If you have installed AllTalk in a custom Python environment, I will only be able to provide limited assistance/support. AllTalk draws on a variety of scripts and libraries that are not written or managed by myself, and they may fail, error or give strange results in custom built python environments.

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**

Getting error with parler. Did I miss some install step? I see a parler_requirements.txt but saw no option to install parler.

**To Reproduce**
Steps to reproduce the behaviour:
Install on windows 11
[diagnostics.log](https://github.com/user-attachments/files/16919271/diagnostics.log)

**Screenshots**
![image](https://github.com/user-attachments/assets/7725cb31-6db4-4efa-ad88-843fef09b12e)

**Text/logs**
If applicable, copy/paste in your logs here from the console.

**Desktop (please complete the following information):**
AllTalk was updated: 9/7/2024 - fresh install
Custom Python environment: [yes/no give details if yes] No
Text-generation-webUI was updated: [approx. date] N/A

**Additional context**

**Comment by teddybear082** [comment]
On startup there was no option for parler.  I'm sure I missed an instruction somewhere but can't find it. 
![image](https://github.com/user-attachments/assets/140197cf-fcd1-4686-b0cb-a0296d8668c6)

**Comment by Wiwi937** [comment]
![image](https://github.com/user-attachments/assets/36ef5eec-d371-4128-ab63-b790f96dc609)
Im running into a similar issue, i did a french install on text-generation-webui and i followed all the install intructions to the letter and i get this when i try to enable alltalks tts extension.

**Comment by erew123** [comment]
Hi all

A few things to cover off here. 

### Parler not installed
@teddybear082 I've tested through a full fresh installation today and had no issues. I suspect the problem you have with Parler not being installed is caused by Python's PIP installer or Conda's installer having internet issues. I've seen this a good few times and of course, its outside of my control as its issues somewhere on the internet (github being intermittent, routing issues, firewall issues, issues with your ISP etc). 

There are 2x ways you can try to resolve this:

1) Use `atsetup` to `delete the AllTalk Environment` and run setup again, to attempt a re-install of the environment.

OR

2) Run `start_environment` at the command prompt in the alltalk folder. You can then move into the the `system` and then `requirements` folder and you can run `pip install requirements_parler.txt` to make it install the Parler requirements. Though, note that other requirements beyond Parler could have failed to install, so there could be other potential issues.

### Managing/Downloading models/engines after First time start up
@teddybear082 Parler is not available/listed as part of the first time start-up and you can manage/download the Parler models. I've made this a bit clearer on the initial start-up splash screen.

![image](https://github.com/user-attachments/assets/a24a31ec-ce8c-49d1-a834-9e2097ba9e67)

![image](https://github.com/user-attachments/assets/b12731eb-6eed-42a0-99c6-5297468ffd72)

### FFmpeg not installed
@Wiwi937 This is either a similar internet related internet issue as stated above OR you did not start Text-generation-webui's Python environment before running the installation routine.

Either way, I would suggest you re-run the routine. So:

- at a command prompt, go to your text-generation-webui folder and run `cmd_windows.bat` to start text-generation-webui's python environment, and then go to the `extensions` folder and the `alltalk_tts` folder and re-run atsetup and `Apply/Re-Apply the requirements for Text-generation-webui.` which should install ffmpeg as part of that process.
- 
![image](https://github.com/user-attachments/assets/bd5b7170-2f8d-4ab0-99e2-e2fc8ba78582)

Worst case, you can run the `cmd_windows.bat` then move into Text-generation-webui's `\text-generation-webui\installer_files\conda\Scripts` folder, and manually install it with the following:

`conda.exe" install -y conda-forge::ffmpeg`

Thanks

**Comment by teddybear082** [comment]
Thanks!

**Comment by joshgura** [comment]
i tried running parler from alltalk beta's gradio interface and it threw an error, and alltalk beta won't start anymore, probably because the configuration setting is written to a file and it's trying to load parler on startup. 

`Traceback (most recent call last):
  File "/run/media/username/FIRESTORE/alltalk_beta/alltalk_tts/tts_server.py", line 171, in <module>
    loader_module = importlib.import_module(f"system.tts_engines.{engine_loaded}.model_engine")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/username/FIRESTORE/alltalk_beta/alltalk_tts/env/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/run/media/username/FIRESTORE/alltalk_beta/alltalk_tts/system/tts_engines/parler/model_engine.py", line 35, in <module>
    from parler_tts import ParlerTTSForConditionalGeneration
  File "/run/media/username/FIRESTORE/alltalk_beta/alltalk_tts/env/lib/python3.11/site-packages/parler_tts/__init__.py", line 8, in <module>
    from .modeling_parler_tts import (
  File "/run/media/username/FIRESTORE/alltalk_beta/alltalk_tts/env/lib/python3.11/site-packages/parler_tts/modeling_parler_tts.py", line 29, in <module>
    from transformers.cache_utils import (
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers.cache_utils' (/run/media/username/FIRESTORE/alltalk_beta/alltalk_tts/env/lib/python3.11/site-packages/transformers/cache_utils.py)
[AllTalk TTS] Warning TTS Engine has NOT started up yet. Will keep trying for 240 seconds maximum. Please wait.
[AllTalk TTS] Warning Mechanical hard drives and a slow PCI BUS are examples of things that can affect load times.
[AllTalk TTS] Warning Some TTS engines index their AI TTS models on loading, which can be slow on CPU or old systems.
[AllTalk TTS] Warning Using one of the other TTS engines on slower systems can help ease this issue.
`

I also tried entering the env and pip install requirements_parler.txt, but that throws an error too:

`ERROR: Could not find a version that satisfies the requirement requirements_parler.txt (from versions: none)
ERROR: No matching distribution found for requirements_parler.txt
`

i looked in the requirements_parler.txt document and it's only a git command:

`git+https://github.com/huggingface/parler-tts.git`

suppose i want to manually install this with a git clone operation, how do i tie that into the alltalk beta's file structure?

I would reinstall all the requirements, but i just did that yesterday to solve a 'transformers' related error.

**Comment by erew123** [comment]
Hi @joshgura I am away travelling at the moment, so have limited access to reply. What I can say is that a new version of the Coqui TTS engine was released yesterday and that **may** be messing/have changed the tranformers version installs (Being away, I am unable to test).

You can try running `start_environment` at the command prompt and running `pip install --force-reinstall git+https://github.com/huggingface/parler-tts.git` which should re-clone and reinstall of everything parler, though, that **may** impact Coqui TTS engines working. (cannot say, I am unable to test ATM).

That should get you in a stable position as far as Parler though

**Comment by illtellyoulater** [comment]
> 2\. pip install requirements_parler.txt

shouldn't that be: `pip install -r requirements_parler.txt` ?
