### ISSUE TITLE
[alltalkbeta] coqui-tts 0.24.1 requires transformers<4.41.0,>=4.33.0

### ISSUE THREAD

**Issue by xdax1** [erew123/alltalk_tts#332]
Hello, I get an error at the end of the installation.
`  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.28.0
    Uninstalling protobuf-5.28.0:
      Successfully uninstalled protobuf-5.28.0
  Attempting uninstall: transformers
    Found existing installation: transformers 4.40.2
    Uninstalling transformers-4.40.2:
      Successfully uninstalled transformers-4.40.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
coqui-tts 0.24.1 requires transformers<4.41.0,>=4.33.0, but you have transformers 4.43.3 which is incompatible.
Successfully installed argbind-0.3.9 asttokens-2.4.1 descript-audio-codec-1.0.0 descript-audiotools-0.7.2 docstring-parser-0.16 executing-2.1.0 fire-0.6.0 flatten-dict-0.4.2 future-1.0.0 ipython-8.27.0 jedi-0.19.1 julius-0.2.7 markdown2-2.5.0 matplotlib-inline-0.1.7 parler_tts-0.2 parso-0.8.4 prompt-toolkit-3.0.47 protobuf-3.19.6 pure-eval-0.2.3 pyloudnorm-0.1.1 pystoi-0.4.1 randomname-0.2.1 sentencepiece-0.2.0 stack-data-0.6.3 termcolor-2.4.0 torch-stoi-0.2.1 traitlets-5.14.3 transformers-4.43.3 wcwidth-0.2.13
** Clean Environment **
Will remove 1 package cache(s).`

many times I tried to install from scratch and tried to manually install different versions but still nothing
[diagnostics.log](https://github.com/user-attachments/files/16919479/diagnostics.log)

**Comment by erew123** [comment]
Hi @xdax1 

This is an acceptable conflict and will specifically cause an issue at this point. 

Parler-TTS have set their base requirements for transformers higher than XTTS does as an engine allows. My understanding from the Parler devs is that they just didnt test on an earlier version of Transformers, so it doesnt mean it wont work, just that its untested. They set their transformers requirements here https://github.com/huggingface/parler-tts/blob/main/setup.py

I've been waiting on the code for XTTS to be updated/released so that both versions match and work is being performed on this, https://github.com/idiap/coqui-ai-TTS/commit/7014782ad4fedea1d5097bb3010fe77c3a386267

Hopefully this will be resolved sometime soon in future, but you should find all TTS engines do work fine, regardless of the message above.

Thanks

**Comment by xdax1** [comment]
Thanks for the reply, then I don't understand why it doesn't work for me, I start after installation and it immediately shuts down, and that's the only error I had during installation.

**Comment by erew123** [comment]
Hi @xdax1 

Please open a command prompt, go to the alltalk_tts folder and from there run `start_alltalk.bat`. Do not just double click on the batch file from the Windows interface as you will not see any error messages as Windows will just close the command prompt window.

Additionally, I note from your diag file, that you have re-named the folder `alltalk_tts-alltalkbeta`. You may find that the dash `-` in the folder path will cause issues with Python as it does sometimes have issues with this. 

Finally, just re-naming the folder will affect all the batch files, depending on when you re-named the folder, as they have to point to the correct path, and the files are build dynamically when atsetup.bat is run. If you re-name the folder you could:

1) edit the batch files to match the correct file paths.
2) delete the batch files and the alltalk_environment and re-run setup.

Thanks
