### ISSUE TITLE
Error 500 with Silly Tavern

### ISSUE THREAD

**Issue by Webslug** [erew123/alltalk_tts#338]
Error 500 with Silly Tavern and AllTalk

I seem to get this error when ever I try and generate audio from Silly Tavern.... I am running as an administrator and have Python installed.  Various other TTS plugins have worked in the past and I was eager to give this one a go. Silly Tavern connects with no problems.  However I cannot see a list of voices in the module menu.

I only downloaded AllTalk and Silly Tavern today 10/09/24

* Issues Error 500
* No voices presented in the drop down list in the AllTalk module settings in SillyTavern

Here is the error I receive.
Error: HTTP 500: {"status":"generate-failure","error":"An error occurred"}
![err1](https://github.com/user-attachments/assets/415e5922-64c3-47ea-a048-ae12149a9841)
![err2](https://github.com/user-attachments/assets/b033e9b8-a47e-47e5-8e6f-1d2c047b9ae4)

AllTalk was updated: 10/09/24
Python environment: Python 3.11

**Additional context**
[AllTalk Startup]←[94m     _    _ _ ←[1;35m_____     _ _     ←[0m  _____ _____ ____
[AllTalk Startup]←[94m    / \  | | |←[1;35m_   _|_ _| | | __ ←[0m |_   _|_   _/ ___|
[AllTalk Startup]←[94m   / _ \ | | |←[1;35m | |/ _` | | |/ / ←[0m   | |   | | \___ \
[AllTalk Startup]←[94m  / ___ \| | |←[1;35m | | (_| | |   <  ←[0m   | |   | |  ___) |
[AllTalk Startup]←[94m /_/   \_\_|_|←[1;35m |_|\__,_|_|_|\_\ ←[0m   |_|   |_| |____/
[AllTalk Startup]
[AllTalk Startup] ←[92mConfig file check      : ←[93mNo Updates required←[0m
[AllTalk Startup] AllTalk startup Mode   : Standalone mode
[AllTalk Startup] WAV file deletion      : Disabled
[AllTalk Startup] DeepSpeed version      : 0.14.0+ce78a63
[AllTalk Startup] Model is available     : Checking
[AllTalk Startup] Model is available     : Checked
[AllTalk Startup] Current Python Version : 3.11.9
[AllTalk Startup] Current PyTorch Version: 2.2.2+cu121
[AllTalk Startup] Current CUDA Version   : 12.1
[AllTalk Startup] Current TTS Version    : 0.22.0
[AllTalk Startup] Current TTS Version is : Up to date
[AllTalk Startup] AllTalk Github updated : 15th August 2024 at 08:27
[AllTalk Startup] TTS Subprocess         : Starting up
[AllTalk Startup]
[AllTalk Startup] AllTalk Settings & Documentation: http://127.0.0.1:7851
[AllTalk Startup]
[AllTalk Model] XTTSv2 Local Loading xttsv2_2.0.2 into cuda
[AllTalk Model] Coqui Public Model License
[AllTalk Model] https://coqui.ai/cpml.txt
[AllTalk Model] Model Loaded in 15.55 seconds.
[AllTalk Model] Ready
[AllTalk TTSGen] Narrator
[AllTalk TTSGen] You wake with a start, recalling the events that led you deep into the forest and the beasts that assailed you. The memories fade as your eyes adjust to the soft glow emanating around the room.
[AllTalk TTSGen] Narrator
[AllTalk TTSGen] Seraphina's eyes sparkle with warmth and concern as she gazes at you, her hands gently holding yours.
[AllTalk TTSGen] Narrator
[AllTalk TTSGen] You wake with a start, recalling the events that led you deep into the forest and the beasts that assailed you. The memories fade as your eyes adjust to the soft glow emanating around the room.

**Comment by erew123** [comment]
Hi

Although I focus on v2 of AllTalk now, I have tested AllTalk V1 with todays build of SillyTavern:

![image](https://github.com/user-attachments/assets/ef939943-8e82-4971-bd20-bbc0b2ec8c60)

I cannot recreate the issue you are having and it works fine in my tests:

![image](https://github.com/user-attachments/assets/fd85a8e0-fcc3-4e2d-b763-970ee129e52c)

The specific error message you show above in your screenshot, is caused by no Narrator voice being specified when trying to generate TTS, which is the knock on effect

I would suggest trying the following:

1) Start AllTalk before you start SillyTavern, to make sure that AllTalk is available for SillyTavern to communicate with and see if that resolves the issue.

2) You can edit out the AllTalk settings, saved by SillyTavern, in its configuration file. The file is stored in `\SillyTavern\data\default-user` and called `settings.json`. Take a copy of the file before making any changes. 

In that file you will find a section like the following that you can delete out and save the file (highlighted in blue):

![image](https://github.com/user-attachments/assets/92ab54cd-c4ab-42cb-8075-b98fb847b6c9)

Then re-load SillyTavern.

3) Check that generally AllTalk is working from its settings page, in the Demo/Test area http://127.0.0.1:7851/

4) Migrate to AllTalk V2 https://github.com/erew123/alltalk_tts/tree/alltalkbeta and follow the instructions to update SillyTavern's AllTalk add in (the instructions are in the built in Documentation).

Thanks
