### ISSUE TITLE
DirectML support

### ISSUE THREAD

**Issue by nonetrix** [erew123/alltalk_tts#354]
**Is your feature request related to a problem? Please describe.**
I use Windows currently because Linux was crashing for some reason, but I also have a AMD GPU :(. ROCm support doesn't seem planned, but DirectML would allow for AMD, Intel, Qualcomm and actually NVIDIA(no real reason to) to be supported to some degree if not as ideal

**Describe the solution you'd like**
DirectML support

**Describe alternatives you've considered**
I mean Vulkan has similar thing, but PyTorch doesn't support that really, maybe CPU support as well could work not sure how good or bad that would be honestly lol

**Additional context**
None that I can think of

**Comment by erew123** [comment]
Hi @nonetrix 

I am keeping an eye on this kind of thing. The issue is that the TTS engine manufacturer (Rhapsidy for Piper, Coqui/idiap for XTTS etc, so on and so forth) would have to either directly support DirectML or ROCm in their engine for the TTS model, OR, things like DirectML would have to support faking CUDA calls (pretending to be a NVidia card and dealing with its requests accordingly for the other GPU hardware).

There was work with ROCm/AMD to get CUDA calls working with ZLuda https://github.com/vosen/ZLUDA and I believe that SCALE also support direct CUDA calls for AMD cards. ZLuda got legally canned (check their site), though I suspect AMD may be bringing something to the market in another way in time (is my guess/personal belief).

Im not sure what the state of play is with DirectML, though I am loosely keeping an eye on it, and I suspect they are closely watching what AMD do. Obviously Microsoft wont want to annoy Nvidia, but if AMD can slip support in, Im sure they would give it a go. 

If the TTS engine Developer of any TTS engine directly support DirectML, as long as its documented, Ill happily include it.

Thanks
