### ISSUE TITLE
Finetuning on GoogleColab fails to launch interface

### ISSUE THREAD

**Issue by plagasul** [erew123/alltalk_tts#382]
**Describe the bug**
Finetuning on GoogleColab fails to launch with the error shown below. 

**To Reproduce**
Launch the Colab notebook either from the link in the wiki or using the notebook in the repo.

Run Requirements cell. OK
Run AllTalk server, choose xttsv2. OK
Stop server.
Run Fine-tuning cell.

**Text/logs**
```
Google Colab Finetuning url: https://xxxx-yyyy-zzzz-llll.trycloudflare.com/

********************************************************************
**** Use the above URL to connect to Finetuning on Google Colab ****
********************************************************************
************* Now starting the Finetuning Application **************
********************************************************************

Traceback (most recent call last):
  File "/content/alltalk_tts/finetune.py", line 1671, in <module>
    demo.load(read_logs, None, logs, every=1)
TypeError: EventListener._setup.<locals>.event_trigger() got an unexpected keyword argument 'every'
[FINETUNE] HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
```

**Additional context**

Previous cells seem to work, including cloudflare, gradio and default TTS generation for Alltalk server with xttsv2.

A week ago or so I did not have the same problem, I was able to launch the gradio interface and access it via cloudflare link.

**Comment by plagasul** [comment]
Removing `, every=1` from all `demo.load(...)` fixes this, but afaik I can only make this permanent by cloning the repo? 

Thanks

**Comment by erew123** [comment]
Hi @plagasul I suspect this is due to the recent Gradio update, though its hard for me to test at the moment. Im basing this on the fact you said it was working last week and Gradio have just released a whole new build of the interface. So, what I have done is nail gradio to `gradio==4.32.2` in the colab requirements file. This will only take effect when a whole new Colab is started, github cloned and setup etc.

Hopefully this should solve it, but let me know (or feel free to close the ticket if all works after that change) 

Thanks

**Comment by erew123** [comment]
Hi @plagasul 

I've finally had time to test the change I made and all appears to be fine, so I will close the ticket.

Thanks

![image](https://github.com/user-attachments/assets/f2b185d2-44d9-435f-8791-60f252ba843b)

**Comment by plagasul** [comment]
Yes, I came here to do the same, worked :) thank you
