### ISSUE TITLE
Request to Continue Updating AllTalk V1

### ISSUE THREAD

**Issue by StellarBeing25** [erew123/alltalk_tts#384]
I understand that your focus has shifted to developing AllTalk V2, currently in beta. However, as a user who relies heavily on AllTalk V1 for XTTS, I kindly request that you continue updating V1, including the Coqui engine to version 0.24.2, until V2 reaches a stable release or becomes modular. This would greatly benefit those who solely use AllTalk for XTTS.

**Comment by erew123** [comment]
Hi @StellarBeing25 

I am mostly focussing on v2 (when I get a chance). Im sure you will have caught my statement [here on this](https://github.com/erew123/alltalk_tts/issues/377)

You **should** be able to update V1's version of the TTS engine to 0.24.2 with this method (I cant think of any issues it would raise):

1. Open a Command Prompt.
2. Navigate to the `alltalk_tts` folder.
3. Run `start_environment.bat` to start the Python environment.
4. Uninstall tts `pip uninstall tts`
5. Install the updated coqui-tts `pip install coqui-tts`

Swap the coqui-tts and tts to reverse the procedure if needed.

As for Pytorch versions and such, thats a much more drawn out process that requires 1-2 days of validation on both Windows and Linux, along with building new DeepSpeed wheel files.

Someone has done a PR for updating to later versions of Pytorch, though because of the reason I mention above in my statement, I have not had time to look at this, re-validate it all and there is still the need to build DeepSpeed wheel files. The PR is here https://github.com/erew123/alltalk_tts/pull/307

Thanks

**Comment by StellarBeing25** [comment]
I received a few errors during the update and starting AllTalk (screenshots attached), which would require a minor fix, but it's working great with 0.24.2. Thanks! I hope everything with your family goes well.
![SS1](https://github.com/user-attachments/assets/1dd90a73-0e83-4017-89ba-56616d09cc24)
![SS2](https://github.com/user-attachments/assets/eaf1f29a-d31a-48d6-97ba-a2e11d0de70a)

**Comment by erew123** [comment]
Thanks!

Im going to close this ticket off for now.
