### ISSUE TITLE
LibMambaUnsatisfiableError: Encountered problems while solving:   - package ffmpeg-7.1.0-lgpl_hdf26e36_401 is excluded by strict repo priority

### ISSUE THREAD

**Issue by tre4b** [erew123/alltalk_tts#385]
🔴 Alltalk installed by just using the windows installer process

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

Refuses to install giving the error 

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package ffmpeg-7.1.0-lgpl_hdf26e36_401 is excluded by strict repo priority

**To Reproduce**
Delete and install again.  I have even tried doing this from a CMD with admin rights just in case.
![Screenshot 2024-10-21 141620](https://github.com/user-attachments/assets/5bddc30c-f4e7-4434-8e96-ed455c595bd1)

**Screenshots**
If applicable, add screenshots to help explain your problem.  attached.

**Text/logs**

**Desktop (please complete the following information):**
AllTalk was updated: This is an initial install of Alltalk 2.
Custom Python environment: I have just used the default options of the atsetup.bat.   2 then 1.
Text-generation-webUI was updated: n/a

**Additional context**
It seems like the package manager is blocking the install, however I have chosen no option for using my internal Python, I was assuming it was therfore alltalk is using its own version of python? (there is an option to remove it later in the menu and that has not been done).  FFMpeg does not seem to be listed in the requirements.  I do already have FFMpeg installed at system level for other programs could that be it?  Other than that the setup just drops out and presumably cannot complete.

**Comment by erew123** [comment]
Hi @tre4b 

Im guessing somewhere else on your system you have an installed system wide version of Conda and it has been set to use a strict priority channel. I cannot say why it would be set to strict, only that this must be the case. Conda's details on channels are here here https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html

I believe a global install of Conda will over-ride a custom/local python environment's settings, like the setup is attempting to build. 

You can check your conda's channel priority with `conda config --describe channel_priority` and its typically its "flexible" e.g. 

![image](https://github.com/user-attachments/assets/fec36db4-e66c-4c57-aacc-0e23ad00fc96)

You can set the channel to flexible with this command `conda config --set channel_priority flexible` then re-run setup (though you may need to delete the alltalk_environment folder for setup to run through).

Please note you would have to find the `conda.exe` file to run this. You could try using the one from AllTalk's custom Python environment, which is stored in `\alltalk_tts\alltalk_environment\conda\Scripts\` and that probably will make the change globally. In theory however, you should have a system wide conda install if this issue is coming up, so you should at any command prompt be able to just run the conda command.

If you have an explicit reason to set it back to strict after the install, you can run `conda config --set channel_priority strict` 

Thanks

**Comment by tre4b** [comment]
Hi erew123.   You would be correct, installed way back when I started playing with AI and was trying to run it in a locally installed python.  I don't use that environment at all now, so I deleted Conda and Python so none of that is there any more.

Things ran through for a while and then stopped again.  This time at a different point in the script.

```

The following NEW packages will be INSTALLED:

  faiss-cpu          pytorch/win-64::faiss-cpu-1.9.0-py3.11_h491596c_0_cpu
  libfaiss           pytorch/win-64::libfaiss-1.9.0-h2e52968_0_cpu
  packaging          pkgs/main/win-64::packaging-24.1-py311haa95532_0

The following packages will be DOWNGRADED:

  numpy                               2.0.1-py311hdab7c0b_1 --> 1.26.4-py311hdab7c0b_0
  numpy-base                          2.0.1-py311hd01c5d8_1 --> 1.26.4-py311hd01c5d8_0



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

. was unexpected at this time.
```
As this is a different issue should I take it somewhere else to resolve?

**Comment by erew123** [comment]
This appears to be the people whom make faiss (Facebook actually) have updated their code and created a bug in their installer. They released a version 13 hours ago https://anaconda.org/pytorch/faiss-cpu/files (at time of me writing this).

![image](https://github.com/user-attachments/assets/88308379-abf3-45c7-b3d3-4b26f5f2cbf7)

I might be able to force an older version in the installer, but please give me a little time to look at this and I will get back to you.

**Comment by erew123** [comment]
I assume that Facebook will fix this quite quickly, but I put in place a temp workaround to install an earlier version. 

So at a command prompt, in your `alltalk_tts` folder, run `git pull` which should show atsetup.bat had a change to it, then you can re-run the setup and it should go through.

Thanks

**Comment by erew123** [comment]
FYI, you may need to delete the `alltalk_environment` folder before you attempt to install the standalone environment. Otherwise you get a message saying it cannot find... well. I cant recall, but it says it cant find something in the script, so just delete the alltalk_environment folder first and then install as normal.
