### ISSUE TITLE
Deepspeed

### ISSUE THREAD

**Issue by Gregg245** [erew123/alltalk_tts#394]
🔴 If you have installed AllTalk in a custom Python environment, I will only be able to provide limited assistance/support. AllTalk draws on a variety of scripts and libraries that are not written or managed by myself, and they may fail, error or give strange results in custom built python environments.

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**
I have installed Alltalk for Text gem webui and deepspeed all from your installer, it does not recognize that it is installed, I used the Pytorch 2.2. for4 121 cuda  now in your start up it says that i am running Pytorch 2.4  and cuda 121 which is installed from WebUI, suggestions on how to correct please?

**To Reproduce**
Steps to reproduce the behaviour:

**Screenshots**

**Text/logs**
If applicable, copy/paste in your logs here from the console.

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date]
Custom Python environment: [yes/no give details if yes]
Text-generation-webUI was updated: [approx. date]

**Additional context**

**Comment by erew123** [comment]
Hi @Gregg245 

Please see my note on support here https://github.com/erew123/alltalk_tts/issues/377

and my statement here on running AllTalk as a part of TGWUI here https://github.com/erew123/alltalk_tts/wiki/Install-%E2%80%90-Text%E2%80%90generation%E2%80%90webui-Installation#read-this-before-installing-into-tgwui

In summary, TGWUI has moved its requirements forward to later versions of PyTorch and I have not had time to validate/update the requirements of AllTalk to a later version of PyTorch as it is a 1-2 day process. Part of which is driven by the fact that Microsoft have moved DeepSpeed's build requirements to work differently. I am assuming you are on Windows as a platform? 

As no-one could currently get DeepSpeed 0.15.x working on the Windows platform, I had to figure this out and eventually ended up building a tool for compilation, along with writing instructions (which took about 20 hours of time to figure out and do, so, as with everything, digs into my time to complete other things).

As such, if you want to compile your own build of DeepSpeed, for PyTorch 2.4.x you can find the tool and instructions here https://github.com/erew123/deepspeedpatcher/ however, I cannot state if there are any other requirements that may need updating/cause issues.

Otherwise, I would suggest using the remote extension option for AllTalk and using AllTalk as a standalone installation, until I have had time to re-work AllTalk's requirements to work on PyTorch 2.4.x 

Standalone installation instructions here https://github.com/erew123/alltalk_tts/wiki/Install-%E2%80%90-Standalone-Installation

Remote Extension details here https://github.com/erew123/alltalk_tts/wiki/Text%E2%80%90generation%E2%80%90webui-Remote-Extension

Directly installing AllTalk into TGWUI's Python environment will be done when I have time/am able to do that. As per my statement, I am mostly away from home/my computer I can code/test on, caring for a critically ill family member, which restricts what/when I am able to do things.

Thanks

**Comment by Gregg245** [comment]
Thank you for your reply I appreciate it
