### ISSUE TITLE
Cleaner Splitting of Finetuning Voice Samples

### ISSUE THREAD

**Issue by Yohrog** [erew123/alltalk_tts#418]
**Is your feature request related to a problem? Please describe.**
When creating a dataset with the finetuning utility, the samples very often get split in the middle of words. This causes a lot more work in dataset validation and/or degraded quality of the resulting finetune.

**Describe the solution you'd like**
At least for datasets with clean audio, it'd be better to consider moments of silence in the audio as potential split points, since that would reduce the likelihood of splitting the audio in the middle of a word, which would result in fewer errors that need to be fixed in validation.

**Describe alternatives you've considered**
Nothing I can really think of. The audio I use for finetuning is very clean initially, but the way it's split makes the finetuning results much worse.
I have considered splitting the samples manually into lengths that won't need to be split any further to fit into the 20 second max length, but with a lot of samples this becomes a pain quickly. 

**Additional context**
I could write a script for it, but then I'd rather contribute it to the project, since I actually really like the finetuning utility. Despite having experience with model training, this makes the process much simpler. Thanks for all the hard work!

**Comment by erew123** [comment]
@Yohrog are you on the new version? 

![image](https://github.com/user-attachments/assets/87bd405a-64dc-4fe7-a198-8a1b1eb97822)

It is possible to have a play with this line here to adjust the gap allowance/detection. But you also have the min/max length and VAD in the main interface.

**Comment by erew123** [comment]
Sorry, meant to drop this link https://github.com/erew123/alltalk_tts/blob/alltalkbeta/finetune.py#L1521

thats the line of code that can be adjusted, though Ive not exposed it to the interface

**Comment by erew123** [comment]
Its actually possible I have one wrong. That function gets called twice:

[merge_short_segments](https://github.com/erew123/alltalk_tts/blob/alltalkbeta/finetune.py#L1171)
setting a 0.3

https://github.com/erew123/alltalk_tts/blob/alltalkbeta/finetune.py#L1878
setting a 0.5

those are at different points in dealing with breaking up the larger files and then oversized files. Its possible that one thats the 0.5 is incorrect.... or the 0.3... one of the two is wrong. 

Sorry.. been too busy coding and other life stuff

**Comment by erew123** [comment]
Oh, well... there will be plenty of those coming up.... Ill let you be the first to know... Ive just released the final build of AllTalk v2 about 30 minutes ago..... and Im sure Ive missed something/there will be a bug! :/

**Comment by erew123** [comment]
@erew123 Here is a snippet of what I was discussing with someone (their words). They have written a lot/do a lot of training of different TTS models, so they know their stuff.

---

If i may some give some constructive points of criticism or concepts to maybe look into...

The ideal segmentation strategy is a gaussian distribution of audio/text. In your case the range is 6-30 seconds so most segments should be around the 18 second point and fan out from there to each end. There is a small issue though because that range may be a bit off. We will naturally speak in very short words or sentences in some cases and we want the model to have examples of this type of speech. The general idea here is that were trying to cover the entire spectrum of possible speech patterns, prosody, tones, etc...

Also, xttsv2 has a token and length cap far under 30 seconds. Its confusing because within their code and documents it does appear that 30 seconds is allowed. I think what happened was they used functions from other models source code and those models allow for greater depth. Because you are supporting several different models I would maybe add an asterisk where different models prefer different ranges and 6-30 seconds is not absolute and may be more or less than ideal. A general range I would use is 1.2 seconds to ~18 seconds.

---

**Comment by erew123** [comment]
@Yohrog FYI, finetuning targets 2 seconds as a minimum (Targets.... of course its not 100% possible to always split that perfectly, hence if it has to it tries to expand the audio capture. If you turn on the diagnostics logging functions, you will see this happening at the command line).

I do think those settings we mentioned earlier probably should both be 0.3

The finetuning process would look something like this (click the <-> arrow at the top right to expand to full screen):

```mermaid
flowchart TD
    A[Input Audio File] --> B[Load with torchaudio]
    B --> C[Convert to Mono if Stereo]
    C --> D[Calculate Original Duration]
    
    D --> E[Resample to 16kHz for VAD]
    E --> F[Move to GPU if Available]
    
    subgraph VAD["VAD Detection (Silero VAD)"]
        F --> G[get_speech_timestamps]
        G --> G1["Speech Detection<br/>threshold=0.3"]
        G --> G2["Min Speech Length<br/>min_speech_duration_ms=250"]
        G --> G3["Max Speech Length<br/>max_speech_duration_s=inf"]
        G --> G4["Min Silence Length<br/>min_silence_duration_ms=400"]
    end
    
    VAD --> H[Initial Speech Segments]
    H --> I["First Merge Pass<br/>max_gap=0.5<br/>min_duration=6.0s"]
    
    I --> J[Scale Timestamps to Original Sample Rate]
    J --> K[Extract Audio Chunks]
    
    K --> L["Second Merge Pass<br/>max_gap=0.3"]
    
    L --> M[For Each Chunk]
    
    subgraph Processing["Chunk Processing"]
        M --> N[Check Duration]
        N --> O{Duration < min_duration?}
        O -->|Yes| P["Attempt to Extend<br/>Add Context Window"]
        O -->|No| Q[Keep Original]
        P --> R[Save WAV File]
        Q --> R
    end
    
    R --> S[Transcribe with Whisper]
    S --> T[Save Metadata]
```

And a breakdown of the possible settings is like this:

1. **threshold=0.3**
   - Range: 0.0 to 1.0
   - Purpose: Determines speech detection sensitivity
   - Effects:
     * Lower (e.g., 0.2): Catches more potential speech, but might include noise
     * Higher (e.g., 0.4): More strict about what counts as speech
     * Current 0.3: Balanced for normal speech

2. **min_speech_duration_ms=250**
   - Purpose: Minimum length to consider something as valid speech
   - Effects:
     * Lower: Catches shorter utterances (like "uh", "ah")
     * Higher: Might miss quick words but reduces false positives
     * Current 250ms: Good for catching single-word utterances

3. **min_silence_duration_ms=400**
   - Purpose: How long silence needs to be to split segments
   - Effects:
     * Lower: More aggressive splitting on brief pauses
     * Higher: Keeps more connected speech together
     * Current 400ms: Natural speech pause threshold

### Merging Parameters

4. **First max_gap=0.5 (Coarse Merging)**
   - Purpose: Initial merging of detected speech segments
   - Current Implementation: More conservative to keep related speech together
   - Used in process_audio_with_vad() for initial VAD output processing

5. **Second max_gap=0.3 (Fine Merging)**
   - Purpose: Final refinement of segments
   - Current Implementation: More aggressive to ensure clean cuts
   - Used in main processing loop for final segment boundaries

**Comment by erew123** [comment]
@Yohrog I think they SHOULD both be the same number otherwise Silero will slice one way, then it may get chopped slightly differently (image below), though Silero is setting the timestamps there will still be an extra gap added (I believe) by using a different msx_gap. So both those numbers **should** be the same. Something I missed in code I guess.

![image](https://github.com/user-attachments/assets/b21b1a77-10e3-48a5-aa92-63cbe0c6a0a9)

**Comment by erew123** [comment]
@Yohrog Feel free to open it on alltalkbeta. 

I will be keeping things there for a while for V2.

Ill close this ticket off (just to make the place look tidy). You're welcome to reply again here, or on your PR of course.

and thanks for looking into it... I can only test X amount of times myself, before Im wasting my time/fed up of doing it, so its nice to have someone else taking a look,
