### ISSUE TITLE
AllTalk TTS Generator - Incomplete audio and special characters removed.

### ISSUE THREAD

**Issue by Suiyou** [erew123/alltalk_tts#52]
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/13854466/diagnostics.log)

**Describe the bug**
AllTalk TTS Generator: It altered the text so certain words did't sound correct and it didn't finished processing all the text given.

**To Reproduce**
I tried to make a complete audiobook, I pasted the complete text (around 23500 words), selected a custom voice wav file for the voice (the same I use all the time for alltalk) and all other settings at default. First I noticed that it removed all of ' "" ... etc, that alters the way TTS reads them, for example "I'm" to "Im". Then it stopped processing at around chunk number 1981 of 2351, no error on the terminal.  Finally I tried consolidating all the generated files using "export to wav" but it didn't do anything.

**Text/logs**
Sorry, I closed the terminal before thinking of submitting a report. 

**Desktop (please complete the following information):**
AllTalk was updated: 06/01/2024 version [AllTalk 1.8d]
Custom Python environment: [yes/no give details if yes]
Text-generation-webUI was updated: 20/12/2023

**Additional context**
Sorry if make a mistake reporting or writing about my issue but English is not my native tongue.

**Comment by erew123** [comment]
I did make a small change yesterday to the allowed characters that pass through, so its probable you got the TTS Generator maybe just before I updated that. They do definitely go through on the current build so you may wish to update that with a git pull

![image](https://github.com/erew123/alltalk_tts/assets/35898566/6413ba9b-ea84-494c-b3c5-846b2554c151)

As for this "Then it stopped processing at around chunk number 1981 of 2351". First off, you know you can export the list to a JSON file, so you can re-import it if needed? (hence start back up where you left off or something.

From your description though, I'm suspecting Your web-browser may have run out of memory or something similar. Obviously you could split the job into 2 jobs (two lots of 1200 sentences) and then join. Or I can test, but obviously, the only way I can do that, is to generate something that big and see what happens. What web-browser are you using and do you know what splitting size you used? I've got a 32GB system, so I can try replicate and see what happens with a system with larger memory (see how much its using etc).

BTW, you wont see anything at the console as the splitting etc is happening in the web-browser, which fires it over to the console side of AllTalk.

LMK on the browser+split size and Ill give it a shot!

**Comment by erew123** [comment]
I've update the TTS Generator. I've added pagination so on screen display of the generated TTS, so you see pages of 100 files at a time, across multiple pages. There's a "No Playback" option in the playback menu, which reduces audio being sent and cached by your browser. I've done some other bits to try clear up any memory allocation issues (where possible). 

Obviously, I haven't managed to test this as far as generating 20,000+ words as Ive not had enough time on my system to do that. Ill try leaving it generating later.

**Comment by Suiyou** [comment]
> "I did make a small change yesterday to the allowed characters that pass through, so its probable you got the TTS Generator maybe just before I updated that. They do definitely go through on the current build so you may wish to update that with a git pull"

I reinstalled alltalk from scratch because I had a error when doing a git pull and now those characters go through perfectly.

> "As for this "Then it stopped processing at around chunk number 1981 of 2351". First off, you know you can export the list to a JSON file, so you can re-import it if needed? (hence start back up where you left off or something."

I saw the video so I knew about that option, I did saved the JSON file and tested reloading, that part works great, but since I couldn't make the button to join the files work (I tested in two browsers, Opera and Chrome) I decided to wait for feedback. Even now the save dialog doesn't show up (after reinstalling alltalk). It's crossed my mind that it could be a memory issue but I tested larger files using the "Demo/Test TTS" generating files of over 6 hours without issues except those inherent to coqui like a warning about possible artifacts or sound getting cutoff becasuse of the length.

----------------------------------------------------------------------
I was writing my reply but a had to cook dinner, when I got back I saw your new comment about the update, I'll try again. Thanks.

**Comment by erew123** [comment]
I know you said you have DeepSpeed installed, but were you in the correct Python environment when running it? 

I can see you have it installed inside of Text-gen-webui. So if you ran AllTalk as a standalone, you did start Text-gen-webui's Python environment first with `cmd_windows.bat`, then move into the AllTalk folder and `python script.py` otherwise it wont load the DeepSpeed (unless you are just loading Text-gen-webui to load AllTalk).

I know you could have run the diagnostics WITHOUT being in text-gen-webui, but it does look like you are in the Text-gen-webui environment and you dont have CUDA installed.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/fbda5060-b1fe-447e-98cd-fe6b1ebaface)

![image](https://github.com/erew123/alltalk_tts/assets/35898566/81888b6a-555c-41be-bdd9-e3296c51fcec)

Does it say DeepSpeed True or False in the console, when Generating?

**Comment by erew123** [comment]
So overnight I ran the following:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/3bf8206d-772b-4f7c-a6fc-6575bd55553f)

Used the `No Playback` option and left it to it. This ran through fine, giving me 10x pages of generated TTS. What I did hit though was a hard web-browser limit of generating a combined audio of 1GB+, so I've added a splitter that will batch groups together so that you generate just less than 1GB files:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/97b520e3-cc66-4457-803a-2044a0bafbcb)

A batch of 600 is on the edge of 1GB (depending on the average size of files generated (larger split will make larger audio TTS files).

The other possible advantage of generating smaller batches when you export, is that there's a lower memory requirement for smaller batches. 

Obviously, another update to get these changes. And check your Python environment as I mentioned above.

**Comment by Suiyou** [comment]
I left it running overnight too and it had processed roughly 2/3 of the text without issues but it was too slow so I reinstalled everything (saving the files and json to continue from there). This is what I did:
[Terminal_log.txt](https://github.com/erew123/alltalk_tts/files/13861098/Terminal_log.txt)

I enabled deepspeed in the text-generation-webui, I opened alltalk settings to check and I had to change it there too, opened  AllTalk TTS Generator, increased the number of chunks to 8, selected no playback, loaded the json file, pasted the rest of the text and pressed Generate TTS. That first generation took 208.04 seconds and the audio file was 76.8 seconds, quite a bit slow. 

Later I noticed that I was getting the warning about text length:

[AllTalk TTSGen] The question came so abruptly that it took me a moment to process what she was talking about. “Oh yeah, the one who set off the alarm in the courtyard?” “May…be some idiot from our…class.” As I wondered why Yano-san would assume that, I recalled something— though I didn’t do it of my own volition. “Nakagawa-san was saying that someone threw her shoes out into the yard. Maybe whoever was here yesterday dropped them.” “That’s day…time…talk.” “But them dropping them might’ve happened at night,” I pointed out. Yano-san fell silent despite her initial protest, as though having accepted this explanation. I ignored her immediate, childish reply of, “Can you…prove it?” “If it is someone from our class, I wonder who.” “Someone who hates Yuri…ko-chan.” By Yuriko-chan she meant Nakagawa. When I thought about the people who hated her, a single human immediately came to mind. Not a monster, a human.
[!] Warning: The text length exceeds the character limit of 250 for language 'en', this might cause truncated audio.
[AllTalk TTSGen] 169.70 seconds. LowVRAM: false DeepSpeed: True

So I stopped it again, saved everything and checked cuda:

C:\Users\shado\pinokio\api\text-generation-webui>cmd_windows.bat
(C:\Users\shado\pinokio\api\text-generation-webui\installer_files\env) C:\Users\shado\pinokio\api\text-generation-webui>pip show torch
Name: torch
Version: 2.1.2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: C:\Users\shado\pinokio\api\text-generation-webui\installer_files\env\Lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, auto-gptq, autoawq, deepspeed, encodec, exllama, exllamav2, flash-attn, lm-eval, openai-whisper, optimum, peft, timm, torchaudio, torchvision, trainer, TTS

It seems that I haven't installed it properly, I'm going to start from scratch (text-generation-webui + alltalk). Sorry if it's no valuable feedback I need to start learnig python. I'll report back when I finish, thanks.

**Comment by erew123** [comment]
Hey no probs! Im just re-running the test now and this has taken me 1 hour (on a 4070 mind)
![image](https://github.com/erew123/alltalk_tts/assets/35898566/d9cf3118-eea3-48a5-9ec8-4d418e88edd8)

Its seeing that DeepSpeed is installed, but, because Pytorch doesnt have CUDA installed, its not actually activating DeepSpeed. T

The problem you have is that your Text-gen-webui environment doesnt have Pytorch installed with CUDA. 

As for what you did with the AllTalk setup etc, that looks fine! 

You can in theory just install PyTorch with CUDA into your Text-gen-webui environment.....(step 5 here after running cmd_windows.bat to start the text-gen-webui Python environment) https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-option-2-i-wish-to-do-a-custom-install-of-alltalk ............. BUT.. I cant say if there will be knock on impacts from that.

So you may find it better to install afresh, then you know all is good. Do your pip show torch at the end of install (and after running cmd_windows.bat) and check that now says it has cu121 or cu118 on it.. and all should be good for installing DeepSpeed etc. You will probably find Text-gen-webui runs models faster too.

**Comment by erew123** [comment]
Oh and I added some notes about throughput and exporting. To save me re-writing them here you can find it all here https://github.com/erew123/alltalk_tts?#-alltalk-tts-generator

**Comment by erew123** [comment]
Oh and that 1x hour of generation, the 58,000 words... split into 2x files generated just over 5 hours of audio.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/ef50d6c4-303f-44c1-8aab-683372376601)
![image](https://github.com/erew123/alltalk_tts/assets/35898566/bcd2829d-9e6d-4181-9965-905ae1d02a2c)

**Comment by Suiyou** [comment]
Ok I reinstalled Text-gen-webui and alltalk, now cuda shows properly (cu121) and after activating deepspeed it went much faster, 41 minutes resulted in 2.5 hours of speech. The only thing I couldn't get to work is " Export to Wav", I don't know how to give feedback on that issue since it doesn't show anything on terminal, I tried different splits and nothing.
So I used chatgpt (I really need to learn python) to make a script that using ffmpeg, concatenates all the files according to the json (with a silence of 0.5 sec. in between) and makes an mp3 at the end.
[concatenate_wav_files.txt](https://github.com/erew123/alltalk_tts/files/13864785/concatenate_wav_files.txt)
Thanks for all the help troubleshooting and great work with the program.

**Comment by erew123** [comment]
> The only thing I couldn't get to work was " Export to Wav", I don't know how to give feedback on that issue since it doesn't show anything on terminal

Ah.. not your fault.. my fault! Somehow I obviously uploaded the incorrect version! Corrected now!! Sorry! umm update again and it should be fine!

**Comment by erew123** [comment]
> concatenate_wav_files.txt

Thanks for sharing. This is one of the reasons why I made the list exportable... it allows flexibility for people to do their own things if they like.

The problem is corrected though :)
