### ISSUE TITLE
requirements mismatch?

### ISSUE THREAD

**Issue by theinhumanity** [erew123/alltalk_tts#7]
text-generation-webui installed torch 2.1.2 with cuda 121 for me. The nvidia requirements file shows its installing for torch 2.1.0 and cuda 118. I tried changing this, but it still didnt let me boot up alltalk, even after trying everything in the troubleshooting section.

**Comment by erew123** [comment]
The requirements file is actually specifying greater than or equal to:

torch>=2.1.0+cu118

torch `>` (means greater than) `=` (or equal to) 2.1.0+cu118

So its demanding a minimum level of Torch 2.1.0 with cuda 11.8 or greater.

**Comment by erew123** [comment]
If you have a problem beyond that, please double check this [list](https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-i-get-alltalk-startup-warning-tts-subprocess-has-not-started-up-yet-will-keep-trying-for-60-seconds-maximum-please-wait-and-then-it-times-out-after-60-seconds) I'm assuming that's what you mean you've been through?

Id need to know what your start-up error is?

**Comment by erew123** [comment]
If you continue having problems, you're welcome to [update AllTalk](https://github.com/erew123/alltalk_tts/tree/main#-updating)

and you can then [generate me a diagnostics log file](https://github.com/erew123/alltalk_tts/tree/main?tab=readme-ov-file#-how-to-make-a-diagnostics-report-file) so I can help you figure out what's going on.

All the best!

**Comment by theinhumanity** [comment]
does this help?
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/13733271/diagnostics.log)

**Comment by erew123** [comment]
Yes, thanks for that!

Your installed versions of packages are all good! No problems there I can see.

So 2x things I do spot. You're very low on system RAM. Im not sure how much of a problem this will be, however, using the Low VRAM function would probably be an issue for you, if you truly only have the 1.25GB's of memory free. As it uses 2GB of system ram. I'm not sure if this will impact it starting up generally..... 

`INFO:root:System RAM: 1.25 GB available out of 7.97 GB total`

As for the second thing, I'm assuming you didn't run these diagnostics while text-generation-webui was running? 

`INFO:root:Port Status: Port 7851 is in use.`

As I see that port 7851 is already in use. Which would either mean AllTalk has started running its web service OR you actually have something else running on that port.

If Text-generation-webui with AllTalk **wasn't** running... then try following step 5 https://github.com/erew123/alltalk_tts#-alltalk-startup-warning-tts-subprocess-has-not-started-up-yet-will-keep-trying-for-60-seconds-maximum-please-wait-it-times-out-after-60-seconds

Otherwise, please let me know what the problem you get is?

**Comment by erew123** [comment]
Oh, by the way, if it had crashed in some way, that *could* explain why your System Ram was so full... possibly. So it may be worth a reboot of your computer and try again (though change the port number too).

**Comment by theinhumanity** [comment]
i figured it out! it turns out my ssd/ram/cpu were so slow it took 70s to load the model. Setting the timeout to 120s fixed the problem for me.
