### ISSUE TITLE
que with a different instance and different voice

### ISSUE THREAD

**Issue by unifirer** [erew123/alltalk_tts#70]
can we have a different instance of the program outputting to a different folder so we can do different voices in a que please?

the program would finish one text chunk in a voice, the next one in que would do a different voice that we specify outputting to a different folder(can be automatic) so that our outputs are not mixed. and then we would get multiple options to combine to wav.

like what handbrake has with a batch que process

i want to input two large texts and have 2 outputs instead of 1

thank you very much

**Comment by erew123** [comment]
Let me clarify on your request. You are asking to generate the same text, but in 2x different voices. And then you want to be able to merge/nit portions of the generated TTS back together to generate the final exported WAV file, where different sections would be read by different voices (as you choose)?

**Comment by unifirer** [comment]
Thank you for your reply
  

  
I'm asking for two different voices for two different books to output    to two    different files but they are not related to each other and are not joined together.   
  

  

  

  
  
  
  
  
>

**Comment by erew123** [comment]
Now you're up and running with this, back to this question. So each time you run a generation, the files created are unique, so if you ran one generation with one lot of text and the voice of your choosing, you would have files `A, B, C....... etc` and you can save that off as a JSON list or Export to a combined wav file.

If you clear the list and changed the text and/or voice, or even just even left the same text and voice in there, but hit generate again, you will get completely new files generated that will sit alongside the existing files, so `1, 2, 3.... etc`. Again you can export that list to JSON or to a combined wav file.

In the output folder you would have files `A, B, C...etc 1, 2, 3..... etc`. Until you delete the originally generated wav files, you can just re-load the JSON files to regenerate individual bits or export the list to a combined wav file. 

Now theoretically speaking (not that Ive tried this) If you open 2x web pages and set one off with `voiceA` and `textA` and you set the off with `voiceb` and `textb`, this would result in a race condition I believe where it will shuffle the 2x generations together, due to the way each web page is waiting for a JSON response. Is it possible to work around this in future, probably yes, it may be as simple as adding a unique ID to each generation request and checking for it on each return OR it may be a very large re-write of the API, generator and other such things. It would be something I would have to think on. 

You can however, as I mention at the start, just create the 2x generations individually and still have access to edit, change, regenerate parts as needed and export their individual list to JSON and re-load that (until you delete the original files). Does that at least cover off your basic request a partial solution? 

Thanks

**Comment by unifirer** [comment]
"clear the list and changed the text and/or voice, or even just even left the same text and voice in there, but hit generate again,"
  

  
It sounds like it's not a que   
  

  

  

  
  
  
  
  
>

**Comment by erew123** [comment]
Ok, so you are basically saying you want to be able to throw multiple texts at it, as raw text or text files of some sort and have them each generate based on settings you set for each document.

This is possible, but due to web-browser limitations, this would more than likely be a very large re-write. Not just the web interface, but potentially the API suite and other things. Or I write a whole separate python script/gradio maybe to handle this. I've added a note on here as something that's been requested, but being such a large thing, it may be a version 2 thing.

https://github.com/erew123/alltalk_tts/discussions/74
