### ISSUE TITLE
Move tts_chunk_player.html from /static to a template render

### ISSUE THREAD

**Issue by stratus-ss** [erew123/alltalk_tts#78]
**Is your feature request related to a problem? Please describe.**

When attempting to run alltalk on a remote host which has the GPUs in it, the `tts_chunk_player/tts_chunk_player.html` does not render properly as it is hard coded to be directed at 127.0.0.1

I have worked around this problem by adding this:

` const baseURL = "http://<host>:<port>" ` in the script definition and then changed each one of the references to use `baseURL` like this:
```
const response = await fetch(`${baseURL}/api/tts-generate`
```

This works but is not ideal.

**Describe the solution you'd like**

I was going to write a PR for this but then realized that this page is being served via fastAPIs static files which does not support passing in parameters. A possible solution is to attempt to read and parse the `confignew.json` again in the static file but this can lead to a duplication of effort.

It may be best to move this from a static `app.mount` to the same `template.render` like the `admin.html` page uses.

Additionally, it might be good to note in the docs (which are already quite good btw) that if you wanted to serve on anything other than local host you should edit the `confignew.json`.

Finally, it may be worth noting that other projects using gradio will set the listen address to `0.0.0.0` which does not work in this case due to the way certain files that are being rendered behave.

**Additional context**

This idea/solution will not fix the links in the getting started page which also still point to local host. If you have a preferred method I am happy to investigate that path and make an initial PR

**Comment by erew123** [comment]
Hey no probs! 

Yes this kind of thing was on my hit list, but I've wanted to sit back a little and just make sure things are stable for a while as I was firing out code every few days. 

However, I've done a quick code update for the TTS generator, so you are welcome to pull an update. What I've set it to do is pull these variables from the actual browser window, so as you have to load the page from the AllTalk server, be it IP address, dns address or whatever, it will always point back to the location of the AllTalk server. 

    var protocol = window.location.protocol;
    var host = window.location.hostname;
    var port = window.location.port;
    var baseUrl = protocol + "//" + host + (port ? ':' + port : ''); 

So we don't have to account for FastAPI or anything like that. All the functions will just point to the IP/name the page is loaded from and you have to run the page from AllTalk, webserver, so this should render a universal solution.

As for changing the IP, you should do that through the http://127.0.0.1:7851/ settings page as that will change the confignew.json file for you, but even then only if you need to explicitly serve it on an specific IP I guess, you are correct though, you cant bind it to 0.0.0.0 without using a DNS record or name based routing in some way, back to a specific IP. I'm sure I can pop something in the documentation somewhere. (BTW I'm just adding this detail for anyone else who reads this issue). 

![image](https://github.com/erew123/alltalk_tts/assets/35898566/0bd669ea-7d54-4151-969a-6a7d69e44db9)

The only thing of AllTalk's that's running gradio is the finetuning. Whist it does integrate into the Gradio of Text-gen-webui thats a locally (python) interaction that's occurring there, nothing over any IP's/network. Is it a concern with the Finetuning you are thinking about?

Thanks

**Comment by stratus-ss** [comment]
Wow thanks for the quick fix. I had not considered such a simple JS fix.

Regarding configuration, your suggested method won't work without some hoop-jumping if you are running on a remote machine. How can you access the settings page when its only available over local host? (note: I know you can do some port forwarding jazz to do this, but again from reading through the docs it was unclear what was needed). 

I think it's a valid usecase to be using a remote machine for AI related work, I have a machine stacked with quadros, but I only turn it on when I want to use something on those. At any rate, it is running headless in a basement so without knowing you have to do port forwarding or other such tactics to do the initial config it was a bit of a lift to get up and running

RE: gradio. I was only referencing that as I saw some gradio code. I have no specific concerns with the fine-tuning bits. Hacking on my own Gradio stuff I set the listen port to `0.0.0.0` which was what I was assuming should be happening here. Your explanation cleared that up however.

I'm happy to pitch in somewhere if you have a list of things are are looking for a contributions. This project with the api has the potential to save me some $$ as I won't have to use OpenAPI for what I was looking to do. Happy to see you succeed

**Comment by erew123** [comment]
Yeah, I get what you mean with headless systems. I've popped a note in [here](https://github.com/erew123/alltalk_tts/tree/main?#-other-installation-notes) and then added basic instructions [here](https://github.com/erew123/alltalk_tts/tree/main?tab=readme-ov-file#-i-am-running-a-headless-system-and-need-to-change-the-ip-address-manually-as-i-cannot-reach-the-config-page)

I think that will cover 99% of people running a headless system, as that's not the sort of thing your average user will have setup, so I'm assuming they will have a basic level of technical understanding (if they can get a headless system running).

**I'm happy to pitch in somewhere if you have a list of things are are looking for a contributions. This project with the api has the potential to save me some $$ as I won't have to use OpenAPI for what I was looking to do. Happy to see you succeed**
Well that's great on all counts! :) As I mentioned, I've taken a slight step back for a week or so, because I wanted to reach a point of stability, have people move to up to a code version where I know everything is working without issue, tweak any small changes and have a think about what next. I've actually yet to announce on Reddit/Ooobabooga that I've made a load of changes and any day soon SillyTavern will update and then the AllTalk extension for SillyTavern **may** end up being used by a new audience, so I'm slightly bracing for that in case I get an influx of questions.

However I'm always up for assistance/help/ideas etc. I do keep a loose list of things people ask me for here https://github.com/erew123/alltalk_tts/discussions/74 and obviously I have other ideas rolling around my head. I guess the only thing is I don't want to do is end up with multiple people working on things that overlap/conflict. But if you're interested in working on something that captures your interest and/or you have some ideas for bits you think would improve it, happy to chat them over discuss a general direction.

For now Im going to mark this ticket as closed, but feel free to reply back here, or open a new conversation on the Discussions area.

Thanks
