### ISSUE TITLE
start_alltalk.bat window closes instantly on boot

### ISSUE THREAD

**Issue by MadHatz42** [erew123/alltalk_tts#84]
Hey, its my first time writing a bug report since i dont use github very much so please bare with me, but i didn't see anyone else saying they have this issue and i really want to try this out!

Like the title says after installing alltalk with the atsetup.bat and i go to try and boot it almost instantly closes the window without any warnings or error messages... I've tried to run the installer 5 times on 2 different places on my PC but every time its the same issue, i also tried the atsetup.sh with gitbash and got no further. I'm trying to use the Standalone version for SillyTavernAI if that info helps.

[diagnostics.log](https://github.com/erew123/alltalk_tts/files/14017916/diagnostics.log)

**Comment by erew123** [comment]
Heya!

No problems :) 

I think I know what your problem is, its kind of a github issue! Ill probably update the quick-setup too.

When you download from the top of the page, you always get `-main` added to the zip file name. Conda (the python environment) doesn't like having a `-` in the name of the folder path. It gives a warning error about this, but it may be that when you click to run the file, it closes the window before you see the error.

So I think you should be able to get through this without a full reinstall by changing:

`C:\Users\Izanagi\Desktop\AIChatbots\alltalk_tts-main` 

to

`C:\Users\Izanagi\Desktop\AIChatbots\alltalk_tts`

You will also need to open `start_alltalk.bat` in notepad and make the same change.

I **believe** this will resolve the problem, but, if not, once you have renamed the folder as above. You can delete the `alltalk_environment` folder and the `start_alltalk.bat` file and re-run `atsetup.bat` telling it to install as a standalone. This will rebuild the files+environment for you.

Ill make a proper note about this in the setup!

If you still have problems, let me know.

Thanks

**Comment by MadHatz42** [comment]
I just want to provide an update in case someone else has this issue in the future and thank you for writing an the easy to understand response and the helpful advice! 

I followed your guide step by step renaming everything to "alltalk_tts" but no dice, even after deleting the environment folder and start file, again nothin' but i ran the installer once more just to make SURE nothing was going wrong and lo and behold i spotted an error. 
![Screenshot 2024-01-23 144401](https://github.com/erew123/alltalk_tts/assets/60501678/234d7547-52a5-401a-a2ad-17d06b606141)
I think I installed Visual studio like 2 years ago? so im guessing my version was so out of date the installer failed? 
![Screenshot 2024-01-23 145823](https://github.com/erew123/alltalk_tts/assets/60501678/bb8e3b78-d95e-461c-bab8-baa7bee3e926)
and after a quick update its all working smoothly! 
Thank you again for the response, and as always i shouldn't be trying to install github software at 4 am when im so tired i over look these simple mistakes lol...

**Comment by erew123** [comment]
Ah yeah, that would also do it! Glad you got it sorted though! :) and yes.. 4am is a killer for doing install! hah!

**Comment by Nomi1212453** [comment]
Soooooo, 2025, having the same problem, tried reinstalling Visual Studio and everything still can't get rid of this error... already wasted like 3 hours on this ChapGPT has no clue how to fix it it's just spewing random nonsense 

<img width="958" height="265" alt="Image" src="https://github.com/user-attachments/assets/bf17f03e-cc68-4649-9c88-78fb7f308075" />
