### ISSUE TITLE
Export to Wav in TTS Generator not working

### ISSUE THREAD

**Issue by Taluen79** [erew123/alltalk_tts#97]
The button on the TTS generator that supposes to combine all the audio chunks into one single .wav file does not seems to work. I have tried to test it on multiple different browsers (Firefox, Brave, Edge) but nothing seems to happen when clicking on it, once I have generated a few sententeces and just want to combine them together.

Great work by the way! Especially the documentation which is always the trickiest to cover everything without becoming outdated fast.

**Comment by erew123** [comment]
Hi @Taluen79 

Are you connected to it via its IP address e.g.  http://127.0.0.1:7851/static/tts_chunk_player.html etc....  (link is within the built in documentation).

![image](https://github.com/erew123/alltalk_tts/assets/35898566/ee0d5335-e3cd-4646-82c4-b93133f46f61)

and assuming you are, could you press F12 to bring up the developer console of your web broswer

![image](https://github.com/erew123/alltalk_tts/assets/35898566/fdf8a74d-36a2-4449-8b96-bfb44b8a82a5)

Let me know if there are any error messages within there? 

Thanks

**Comment by erew123** [comment]
@Taluen79 Could I check are you one the most recent build? There was an issue with mime types in the past, but I pushed an explicit exclusion in the web server of AllTalk, so it shouldnt be occurring. 

The mime type will cause the 2nd issue to occur. 

If you let me know what OS you are on, Ill pull the latest build to that OS, check my browsers are up to date and give it a test.

Thanks

**Comment by Taluen79** [comment]
@erew123 

I'm on Windows and just did a git pull. Then I ran a git one-liner and it gave me this output:

* 00b93cf (HEAD -> main, origin/main, origin/HEAD) explicit allowance for ć, ś, ń, ł etc
* c0d01ee Update tts_server.py
* d0ceb2b Update atsetup.sh
* 3231e61 Bumped transformers requirements >=4.37.1
* 32f3b72 Update README.md
*   8c58893 Merge pull request #86 from erew123/dev
|\
| * ff1077f (origin/dev) Update docker-compose-cuda.yml
| * 36d0e92 Update docker-compose.yml
| *   8dfb84d Merge pull request #83 from Josh-XT/main
| |\
| | *   40f2fbf Merge branch 'erew123:main' into main
| | |\
| |_|/
|/| |
| | *   351f46c Merge branch 'erew123:main' into main
| | |\
| | * | 71ba584 Add voices
| | * | b3f53e9 fix typo
| | * | 0ed3cb7 Add modeldownload
| | * | c29de18 add chmod
| | * | ec1d0e8 Check if running in docker
| | * | 12bf008 Run back end without subprocess
| | * | 360f70c Disable deepspeed
| | * | 51c91c3 Fix config
| | * | 81a9f4c Persist config
| | * | cdce751 Use deepspeed
| | * | d750959 Add docker-compose
| | * | bd74de5 Add portaudio19-dev

If it somehow works when you test it, please let me know which browser you are using.

Thanks!

**Comment by erew123** [comment]
Hi @Taluen79 

I've downloaded a full fresh copy onto Windows 11 and tried with both Brave (chrome) and Microsoft Edge. Both worked fine for me e.g. 

![image](https://github.com/erew123/alltalk_tts/assets/35898566/2d35dc1d-1cd3-4018-b077-6a0466f46909)
![image](https://github.com/erew123/alltalk_tts/assets/35898566/d0b32d16-7791-43b3-bd9a-bb4138fe2c7d)

The Mime type allowance is set by the `tts_server.py` file, so you may want to try downloading the current one, over the top of your `tts_server.py` just to make sure that theres nothing strange going on there. So you would go to this link https://github.com/erew123/alltalk_tts/blob/main/tts_server.py and click the download button, saving it over the top of your current `tts_server.py` file. (Restart AllTalk of course).

![image](https://github.com/erew123/alltalk_tts/assets/35898566/3a19cc33-33fa-457f-99bf-f42406a1a990)

If its still not working at that, it _**suggests**_ to me that you may have some Antivirus software or similar that may be filtering the mime types out e.g. Malwarebytes, BitDefender etc. Mainly because the issue followed across browsers, hence its not browser specific, its either specific to the `tts_server.py` not being up to date somehow OR its system specific in some way. If you have something other than Windows Defender, you could try temporarily disabling its Web protection for a few minutes to give it a go.

Thanks

**Comment by Taluen79** [comment]
Hi @erew123 !

That's so weird. I just did a clean git clone on another Windows box and got the same behavior. The only antivirus I ever use is my judgement. So there must be something else at work here. If it works for you and no one else is experiencing this issue, I will try my luck and dig into this when I have the time. You can close the issue. Thanks anyway!

**Comment by erew123** [comment]
Hi @Taluen79 

Just for my own sanity, I setup a new Windows 11 virtual machine and followed through with the "Quick Setup - Standalone Installation" https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-quick-setup-text-generation-webui--standalone-installation as per this video https://www.youtube.com/watch?v=AQYCccDRbaY

I've also double checked on Linux. Neither installation had an issue and both worked fine.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/4941b99a-0502-4182-bc8a-8d753d805e65)

I also double checked that no current downloadable versions of the tts_server.py file is missing anything or could be a different/older version. They all carry the following:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/2573fb44-b4ff-4fb4-a29b-26b73d81e04a)

This setting basically says that all Mime types and Javascript is allowed to be served by the AllTalk webserver and the browser should honour that request. So your browser console showing **"Strict MIME type checking is enforced for module"** suggests that something has gotten into to the middle of the request and filtered it, such as an Antivirus, Proxy, Extension, Firewall, or maybe Javascript is disabled in your web browsers. 

At the point of clicking the Export Wav, the webserver is trying to load "crunker" which is a Javascript bit of code that will be used to combine the files. Because the mime type isnt allowed, it cannot pull down/run that Javascript within your browser, hence the failure.

All I can say for sure is that the code is working correctly and best I can diagnose, its something linked back to the setup on your system(s). Ill close the ticket for now and you're welcome to get back to me if you need.

Thanks

**Comment by executer9648** [comment]
Hi guys, was this solved? i just downloaded both version i.e 1.9 and 2(beta) and i have the same issue.
im on windows10 with vivaldi but i tried also with chrome 
i disabled my AV and ad blocker but stil no good

**Comment by CheekyRaymondo** [comment]
My solution isn't the most elegant, but I used the solution in here:
https://github.com/janeczku/calibre-web/issues/896

Changed the registry entry for .js files to be application/javascript instead of text/plain !

You could also add a new entry for .esm.js files as I think my approach (just changing .js) might have messed up other projects I use, but I'll have to wait and see!

I hope this helps all!

**Comment by JohnF51** [comment]
I tried what you wrote I edited the registers but it doesn't work for me. mom got such a bug in the chrome console 
tts_generator.html:704 Uncaught ReferenceError: exportMP3 is not defined
    at HTMLButtonElement.onclick (tts_generator.html:704:87)
onclick @ tts_generator.html:704By this errorAI
tts_generator.html:1 Uncaught (in promise) Error: the listener indicated an asynchronous response by returning true, but the message channel closed before receiving the response
Could the error be directly in the tts.generator.html script or in howler.min.js or crunker.esm.js? I can't get it to move :(

**Comment by JohnF51** [comment]
I confirm what it  says @CheekyRaymondo that it works I changed the browser to edge and it works great thank you :)

Thank for beautifull alltts @erew123

**Comment by CheekyRaymondo** [comment]
> I confirm what it says [@CheekyRaymondo](https://github.com/CheekyRaymondo) after change registry it works. I changed the browser from chrome to edge and it works great thank you :)
> 
> Thank for beautifull alltts [@erew123](https://github.com/erew123)
> 
> Here is steps to modify the MIME type:
> 
> Open the Registry Editor: Press Win + R to open the "Run" dialog box. Type regedit and press Enter. This will open the Registry Editor. Find the correct path in the registry: Navigate to the following path: HKEY_CLASSES_ROOT.js
> 
> Change the value of the MIME type: You should see an entry called Content Type in the right panel. Double-click on this entry to open a dialog box to edit the value. Change the value from text/plain to application/javascript. Click OK to save your changes. After making these changes, restart the browser for the new settings to take effect. If chrome doesnt work try edge

No worries @JohnF5 !!

In my experience issues usually arise from either not having things in respective environments, or from package dependency issues/incorrect package versions. I would ultimately recommend adding an additional entry for esm.js rather than altering .js in the registry as to avoid breaking anything else; if anyone else can shed light on best practice here that'd prove useful I think.
